// Fixed SOURCE Install/Remove detached signatures, two-App and standalone
// remover purpose facts, not package
// authority, uniform child signers or a Keychain service. Caller retains files.
// Private-key use below exists ONLY in the explicit packaging-example build.
#include "install_producer.h"
#include <CoreFoundation/CoreFoundation.h>
#include <Security/Security.h>
#include <CommonCrypto/CommonDigest.h>
#include <pthread.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdio.h>
#include <sys/param.h>
#include <sys/stat.h>

// Generated by the existing SOURCE-bound native build, NEVER from the package
// descriptor or a runtime environment. Unconfigured builds define only0.
// Configured input additionally defines fixed public *_der byte arrays,
// *_sha256[32], leaf_sha1[20], team[11], public_key_pkcs1_sha256[32] and
// MRK_INSTALL_PRODUCER_RSA_BITS. No private key is compiled or discovered here.
#include "mrk-install-producer-selection.h"
#ifndef MRK_INSTALL_PRODUCER_CONFIGURED
#error producer selection must explicitly configure or disable this adapter
#endif
#if MRK_INSTALL_PRODUCER_CONFIGURED != 0 && MRK_INSTALL_PRODUCER_CONFIGURED != 1
#error producer selection must be a closed SOURCE build flag
#endif
#if !defined(__APPLE__) || (!defined(__aarch64__) && !defined(__x86_64__))
#error producer adapter requires a supported native Mac target
#endif
_Static_assert(sizeof(void *)==8,"supported LP64 adapter only");
_Static_assert(sizeof(mrk_install_producer_report)==136,"fixed Rust/C custody ABI");
_Static_assert(sizeof(mrk_install_producer_signer)==104,"fixed Rust/C SOURCE ABI");

#if MRK_INSTALL_PRODUCER_CONFIGURED
_Static_assert(MRK_INSTALL_PRODUCER_RSA_BITS==2048 || MRK_INSTALL_PRODUCER_RSA_BITS==3072
    || MRK_INSTALL_PRODUCER_RSA_BITS==4096,"fixed RSA/SHA256 signature profile");
_Static_assert(sizeof(mrk_install_producer_leaf_der)>0 && sizeof(mrk_install_producer_leaf_der)<=16384
    && sizeof(mrk_install_producer_issuer_der)>0 && sizeof(mrk_install_producer_issuer_der)<=16384
    && sizeof(mrk_install_producer_root_der)>0 && sizeof(mrk_install_producer_root_der)<=16384,
    "bounded complete SOURCE certificate chain");
_Static_assert(sizeof(mrk_install_producer_leaf_sha256)==32 && sizeof(mrk_install_producer_issuer_sha256)==32
    && sizeof(mrk_install_producer_root_sha256)==32 && sizeof(mrk_install_producer_leaf_sha1)==20
    && sizeof(mrk_install_producer_public_key_pkcs1_sha256)==32 && sizeof(mrk_install_producer_team)==11,
    "complete SOURCE signer pins");
#define MRK_PRODUCER_MAGIC UINT64_C(0x4d524b50524f4432)
static const uint8_t message_domain[]="MobileReleaseKit-package-producer-v2"; // includes one NUL
static const uint8_t remove_message_domain[]="MobileReleaseKit-remove-producer-v1";
_Static_assert(sizeof(remove_message_domain)<=sizeof(message_domain),"remove domain fits original supplied buffer");
typedef struct {
    uint64_t magic;
    pthread_t thread;
    pid_t process;
    uid_t uid; gid_t gid;
    size_t message_size,signature_size;
    uint8_t message[sizeof(message_domain)+MRK_INSTALL_PRODUCER_DESCRIPTOR_MAX],signature[512];
    // Scalar borrowed inputs only. Cleanup never looks up or closes them.
    int outer_fd,code_fd;
    char outer_path[MRK_INSTALL_PRODUCER_PATH_MAX],code_path[MRK_INSTALL_PRODUCER_PATH_MAX];
    struct stat outer_identity,code_identity;
    CFTypeRef values[MRK_INSTALL_PRODUCER_SLOTS];
    mrk_install_producer_report report;
#if MRK_INSTALL_PRODUCER_SIGNING
    uint32_t signature_copied;
#endif
} producer_cell;
_Static_assert(sizeof(producer_cell)<=MRK_INSTALL_PRODUCER_CELL_MAX,"bounded supplied originals, not framework heap");
_Static_assert(MAXPATHLEN==MRK_INSTALL_PRODUCER_PATH_MAX,"fixed Darwin F_GETPATH output bound");
_Static_assert(6*MAXPATHLEN+4*sizeof(struct stat)+1024<=MRK_INSTALL_PRODUCER_CODE_STACK_MAX,
    "explicit path/stat/requirement supplied stack reserve, not Security heap");
static int nonzero(const uint8_t *bytes,size_t size) {
    uint8_t any=0;for(size_t i=0;i<size;i++) any|=bytes[i];return any!=0;
}
static int sha256_matches(const uint8_t *bytes,size_t size,const uint8_t expected[32]) {
    uint8_t actual[32];return size<=UINT32_MAX && nonzero(expected,32)
        && CC_SHA256(bytes,(CC_LONG)size,actual) && memcmp(actual,expected,32)==0;
}
static int source_selected(void) {
    uint8_t sha1[20];
    if (mrk_install_producer_team[10]!=0 || !nonzero(mrk_install_producer_public_key_pkcs1_sha256,32)) return 0;
    for(unsigned i=0;i<10;i++) {
        uint8_t c=mrk_install_producer_team[i];if(!((c>='A' && c<='Z') || (c>='0' && c<='9'))) return 0;
    }
    // SHA1 is compatibility with the existing exact-leaf code requirement only.
    // SHA256 of original DER and exported public key are independent requirements.
    return sha256_matches(mrk_install_producer_leaf_der,sizeof(mrk_install_producer_leaf_der),mrk_install_producer_leaf_sha256)
        && sha256_matches(mrk_install_producer_issuer_der,sizeof(mrk_install_producer_issuer_der),mrk_install_producer_issuer_sha256)
        && sha256_matches(mrk_install_producer_root_der,sizeof(mrk_install_producer_root_der),mrk_install_producer_root_sha256)
        && nonzero(mrk_install_producer_leaf_sha1,20)
        && CC_SHA1(mrk_install_producer_leaf_der,(CC_LONG)sizeof(mrk_install_producer_leaf_der),sha1)
        && memcmp(sha1,mrk_install_producer_leaf_sha1,20)==0;
}
static int original(producer_cell *cell) {
    return cell && cell->magic==MRK_PRODUCER_MAGIC && cell->process==getpid()
        && pthread_equal(cell->thread,pthread_self()) && cell->uid==getuid() && getuid()==geteuid()
        && cell->gid==getgid() && getgid()==getegid();
}
static void failed(producer_cell *cell) { cell->report.failed=1; }
static void unknown(producer_cell *cell) {
    failed(cell);cell->report.unknown=1;
    for(unsigned i=0;i<MRK_INSTALL_PRODUCER_SLOTS;i++)
        if(cell->report.states[i]==1 || cell->report.states[i]==3) cell->report.states[i]=5;
}
static void received(producer_cell *cell,unsigned slot,int required) {
    cell->report.states[slot]=cell->values[slot]?2:4;
    if(required && !cell->values[slot]) failed(cell);
}
static int data_equal(CFTypeRef value,const uint8_t *bytes,size_t size) {
    return value && CFGetTypeID(value)==CFDataGetTypeID()
        && CFDataGetLength((CFDataRef)value)==(CFIndex)size
        && memcmp(CFDataGetBytePtr((CFDataRef)value),bytes,size)==0;
}
static int key_attributes(producer_cell *cell) {
    CFDictionaryRef info=(CFDictionaryRef)cell->values[7];
    if(!info || CFGetTypeID(info)!=CFDictionaryGetTypeID() || CFDictionaryGetCount(info)>64) return 0;
    CFTypeRef kind=CFDictionaryGetValue(info,kSecAttrKeyType),type=CFDictionaryGetValue(info,kSecAttrKeyClass);
    CFTypeRef bits=CFDictionaryGetValue(info,kSecAttrKeySizeInBits),verify=CFDictionaryGetValue(info,kSecAttrCanVerify);
    int64_t number=0;
    return kind && type && CFEqual(kind,kSecAttrKeyTypeRSA) && CFEqual(type,kSecAttrKeyClassPublic)
        && bits && CFGetTypeID(bits)==CFNumberGetTypeID() && !CFNumberIsFloatType((CFNumberRef)bits)
        && CFNumberGetValue((CFNumberRef)bits,kCFNumberSInt64Type,&number) && number==MRK_INSTALL_PRODUCER_RSA_BITS
        && verify==kCFBooleanTrue
        && SecKeyGetBlockSize((SecKeyRef)cell->values[6])==MRK_INSTALL_PRODUCER_RSA_BITS/8
        && SecKeyIsAlgorithmSupported((SecKeyRef)cell->values[6],kSecKeyOperationTypeVerify,
            kSecKeyAlgorithmRSASignatureMessagePKCS1v15SHA256);
}
static int code_role(uint32_t role) { return role==1 || role==2 || role==5; }
#if MRK_INSTALL_PRODUCER_SIGNING
static int sign_role(uint32_t role) { return role==3 || role==6; }
#endif
static const char *code_suffix(uint32_t role) {
    return role==5 ? "/mrk-macos-remove" : role==1 ? "" : "/Contents/Helpers/MobileReleaseKitPayload.app";
}
static const char *code_main(uint32_t role) {
    return role==5 ? "" : role==1 ? "/Contents/MacOS/mrk-macos-entry" : "/Contents/MacOS/mobile-release-kit-desktop";
}
static const char *code_identifier(uint32_t role) {
    return role==5 ? "dev.mobile-release-kit.desktop.remove" : role==1 ? "dev.mobile-release-kit.desktop.entry" : "dev.mobile-release-kit.desktop";
}
static int canonical_path(const uint8_t *path,size_t size,uint32_t role) {
    if(!code_role(role) || !path || size<=1 || size>=MRK_INSTALL_PRODUCER_PATH_MAX
        || path[0]!='/' || memchr(path,0,size)
        || size+strlen(code_suffix(role))+strlen(code_main(role))>=MRK_INSTALL_PRODUCER_PATH_MAX) return 0;
    size_t start=1;
    for(size_t i=1;i<=size;i++) if(i==size || path[i]=='/') {
        size_t n=i-start;
        if(!n || (n==1 && path[start]=='.') || (n==2 && path[start]=='.' && path[start+1]=='.')) return 0;
        start=i+1;
    }
    return 1;
}
static int directory_shape(const struct stat *s) {
    return S_ISDIR(s->st_mode) && (s->st_mode&07777)==0555 && s->st_uid==0 && s->st_gid==0 && s->st_nlink>0;
}
static int directory_equal(const struct stat *a,const struct stat *b) {
    // No padding or read-atime comparison; every nominated identity field matters.
    return a->st_dev==b->st_dev && a->st_ino==b->st_ino && a->st_mode==b->st_mode
        && a->st_uid==b->st_uid && a->st_gid==b->st_gid && a->st_nlink==b->st_nlink
        && a->st_size==b->st_size && a->st_mtimespec.tv_sec==b->st_mtimespec.tv_sec
        && a->st_mtimespec.tv_nsec==b->st_mtimespec.tv_nsec && a->st_ctimespec.tv_sec==b->st_ctimespec.tv_sec
        && a->st_ctimespec.tv_nsec==b->st_ctimespec.tv_nsec && a->st_flags==b->st_flags;
}
static int borrowed_directory(int fd,const char *path,const struct stat *expected) {
    struct stat held={0},named={0};
    char actual[MRK_INSTALL_PRODUCER_PATH_MAX]={0};
    return fd>=0 && fstat(fd,&held)==0 && lstat(path,&named)==0
        && directory_shape(&held) && directory_shape(&named)
        && directory_equal(&held,expected) && directory_equal(&held,&named)
        && fcntl(fd,F_GETPATH,actual)==0 && memchr(actual,0,sizeof(actual)) && strcmp(actual,path)==0;
}
static int borrowed_remove(int fd,const char *path,const struct stat *expected,int directory) {
    struct stat held={0},named={0};char actual[MRK_INSTALL_PRODUCER_PATH_MAX]={0};
    if(fd<0 || fstat(fd,&held)!=0 || lstat(path,&named)!=0 || held.st_uid!=getuid() || held.st_gid!=getgid()
        || held.st_flags!=0 || !directory_equal(&held,expected) || !directory_equal(&held,&named)) return 0;
    if(directory) {
        if(!S_ISDIR(held.st_mode) || (held.st_mode&07022)!=0 || held.st_nlink<=0) return 0;
    } else if(!S_ISREG(held.st_mode) || (held.st_mode&07777)!=0555 || held.st_nlink!=1
        || held.st_size<=0 || (uint64_t)held.st_size>UINT64_C(67108864)) return 0;
    return fcntl(fd,F_GETPATH,actual)==0 && memchr(actual,0,sizeof(actual)) && strcmp(actual,path)==0;
}
static int code_originals(producer_cell *cell) {
    if(cell->report.reserved==5) return borrowed_remove(cell->outer_fd,cell->outer_path,&cell->outer_identity,1)
        && borrowed_remove(cell->code_fd,cell->code_path,&cell->code_identity,0);
    return borrowed_directory(cell->outer_fd,cell->outer_path,&cell->outer_identity)
        && borrowed_directory(cell->code_fd,cell->code_path,&cell->code_identity);
}
static unsigned code_slot(uint32_t phase) {
    switch(phase) {
        case 1:return 0;case 2:return 1;case 3:return 2;case 4:return 3;case 6:return 4;case 7:return 5;
        default:return MRK_INSTALL_PRODUCER_SLOTS;
    }
}
static int code_info_shape(CFDictionaryRef info) {
    return info && CFGetTypeID(info)==CFDictionaryGetTypeID() && CFDictionaryGetCount(info)<=128;
}
static int code_hardened(CFDictionaryRef info) {
    if(!code_info_shape(info)) return 0;
    CFTypeRef flags=CFDictionaryGetValue(info,kSecCodeInfoFlags);
    int64_t number=0;
    if(!flags || CFGetTypeID(flags)!=CFNumberGetTypeID() || CFNumberIsFloatType((CFNumberRef)flags)
        || !CFNumberGetValue((CFNumberRef)flags,kCFNumberSInt64Type,&number) || number<0 || number>UINT32_MAX
        || !((uint32_t)number&kSecCodeSignatureRuntime)) return 0;
    CFTypeRef ent=CFDictionaryGetValue(info,kSecCodeInfoEntitlementsDict),raw=CFDictionaryGetValue(info,kSecCodeInfoEntitlements);
    if(ent && (CFGetTypeID(ent)!=CFDictionaryGetTypeID() || CFDictionaryGetCount((CFDictionaryRef)ent)!=0)) return 0;
    return !((!ent && raw) || (raw && (CFGetTypeID(raw)!=CFDataGetTypeID() || CFDataGetLength((CFDataRef)raw)>4096)));
}
static int code_facts(producer_cell *cell) {
    CFDictionaryRef info=(CFDictionaryRef)cell->values[4];
    if(!code_hardened(info)) return 0;
    CFTypeRef identifier=CFDictionaryGetValue(info,kSecCodeInfoIdentifier);
    CFTypeRef executable=CFDictionaryGetValue(info,kSecCodeInfoMainExecutable);
    CFStringRef required=cell->report.reserved==5 ? CFSTR("dev.mobile-release-kit.desktop.remove")
        : cell->report.reserved==1 ? CFSTR("dev.mobile-release-kit.desktop.entry") : CFSTR("dev.mobile-release-kit.desktop");
    char expected[MRK_INSTALL_PRODUCER_PATH_MAX]={0},actual[MRK_INSTALL_PRODUCER_PATH_MAX]={0};
    int size=snprintf(expected,sizeof(expected),"%s%s",cell->code_path,code_main(cell->report.reserved));
    CFTypeRef der=cell->values[5];
    return identifier && CFGetTypeID(identifier)==CFStringGetTypeID() && CFEqual(identifier,required)
        && executable && CFGetTypeID(executable)==CFURLGetTypeID() && size>0 && (size_t)size<sizeof(expected)
        && CFURLGetFileSystemRepresentation((CFURLRef)executable,false,(UInt8 *)actual,sizeof(actual))
        && memchr(actual,0,sizeof(actual)) && strcmp(actual,expected)==0
        && data_equal(der,mrk_install_producer_leaf_der,sizeof(mrk_install_producer_leaf_der))
        && sha256_matches(CFDataGetBytePtr((CFDataRef)der),sizeof(mrk_install_producer_leaf_der),mrk_install_producer_leaf_sha256);
}
static int code_step(producer_cell *cell,uint32_t phase,mrk_install_producer_report *out) {
    if(!code_role(cell->report.reserved) || cell->report.failed || cell->report.unknown || phase<1
        || phase>MRK_INSTALL_PRODUCER_CODE_STEPS || phase!=cell->report.phase+1) return 0;
    unsigned slot=code_slot(phase);
    if(slot<MRK_INSTALL_PRODUCER_SLOTS && (cell->values[slot] || cell->report.states[slot])) return 0;
    cell->report.phase=phase;cell->report.calls++;
    if(slot<MRK_INSTALL_PRODUCER_SLOTS) cell->report.states[slot]=1;
    @try {
        OSStatus status=errSecSuccess;
        if(!code_originals(cell)) failed(cell);
        if(!cell->report.failed) switch(phase) {
            case 1:
                cell->values[0]=CFURLCreateFromFileSystemRepresentation(NULL,(const UInt8 *)cell->code_path,strlen(cell->code_path),cell->report.reserved!=5);break;
            case 2: {
                SecStaticCodeRef code=NULL;
                status=SecStaticCodeCreateWithPath((CFURLRef)cell->values[0],kSecCSDefaultFlags,&code);
                cell->values[1]=code;break;
            }
            case 3: {
                static const char hex[]="0123456789abcdef";
                char leaf[41]={0},requirement[768]={0};
                for(unsigned i=0;i<20;i++) {leaf[2*i]=hex[mrk_install_producer_leaf_sha1[i]>>4];leaf[2*i+1]=hex[mrk_install_producer_leaf_sha1[i]&15];}
                int size=snprintf(requirement,sizeof(requirement),
                    "anchor apple generic and identifier \"%s\" and certificate leaf[subject.OU] = \"%s\" and certificate leaf = H\"%s\" and certificate 1[field.1.2.840.113635.100.6.2.6] exists and certificate leaf[field.1.2.840.113635.100.6.1.13] exists",
                    code_identifier(cell->report.reserved),(const char *)mrk_install_producer_team,leaf);
                if(size<=0 || (size_t)size>=sizeof(requirement)) {failed(cell);break;}
                cell->values[2]=CFStringCreateWithCString(NULL,requirement,kCFStringEncodingASCII);break;
            }
            case 4: {
                SecRequirementRef requirement=NULL;
                status=SecRequirementCreateWithString((CFStringRef)cell->values[2],kSecCSDefaultFlags,&requirement);
                cell->values[3]=requirement;break;
            }
            case 5:
                status=SecStaticCodeCheckValidity((SecStaticCodeRef)cell->values[1],
                    kSecCSStrictValidate|kSecCSCheckAllArchitectures|kSecCSCheckNestedCode|kSecCSNoNetworkAccess,
                    (SecRequirementRef)cell->values[3]);break;
            case 6: {
                CFDictionaryRef info=NULL;
                status=SecCodeCopySigningInformation((SecStaticCodeRef)cell->values[1],kSecCSSigningInformation,&info);
                cell->values[4]=info;break;
            }
            case 7: {
                CFDictionaryRef info=(CFDictionaryRef)cell->values[4];
                if(!code_info_shape(info)) {failed(cell);break;}
                CFTypeRef chain=CFDictionaryGetValue(info,kSecCodeInfoCertificates);
                if(!chain || CFGetTypeID(chain)!=CFArrayGetTypeID() || CFArrayGetCount((CFArrayRef)chain)<1
                    || CFArrayGetCount((CFArrayRef)chain)>8) {failed(cell);break;}
                CFTypeRef certificate=CFArrayGetValueAtIndex((CFArrayRef)chain,0);
                if(!certificate || CFGetTypeID(certificate)!=SecCertificateGetTypeID()) {failed(cell);break;}
                cell->values[5]=SecCertificateCopyData((SecCertificateRef)certificate);break;
            }
            case 8:if(!code_facts(cell)) failed(cell);break;
            default:failed(cell);break;
        }
        // A known PRE refusal never dispatched the API: armed empty slot is
        // consumed+failed, not an invented reference or uncertain acquisition.
        if(slot<MRK_INSTALL_PRODUCER_SLOTS) received(cell,slot,1);
        if(status!=errSecSuccess) failed(cell);
        if(!code_originals(cell)) failed(cell);
        cell->report.returned++;
        if(phase==MRK_INSTALL_PRODUCER_CODE_STEPS && !cell->report.failed) cell->report.matched=1;
    } @catch (...) {unknown(cell);}
    *out=cell->report;return 1;
}
static unsigned phase_slot(uint32_t phase) {
    if(phase<=8) return phase-1;
    switch(phase) {
        case 9:return 8;case 10:return 10;case 11:return 11;case 12:return 12;
        case 13:return 13;case 14:return 14;case 15:return 15;case 16:return 16;
        case 20:return 17;case 22:return 18;case 23:return 19;case 24:return 20;
        case 25:return 21;case 26:return 22;case 27:return 23;case 28:return 24;case 29:return 25;
        default:return MRK_INSTALL_PRODUCER_SLOTS;
    }
}
#if MRK_INSTALL_PRODUCER_SIGNING
static unsigned sign_slot(uint32_t phase) {
    if(phase>=1 && phase<=8) return phase-1;
    switch(phase) {
        case 9:return 8;case 10:return 10;case 11:return 11;case 12:return 13;
        default:return MRK_INSTALL_PRODUCER_SLOTS;
    }
}
// No arbitrary operation callback. UI suppression is local to each of these
// fixed calls, and restored before any outer caller checkpoint. A known original
// Boolean is restorative input, NEVER permission to adopt uncertain CF outputs.
static void sign_keychain_phase(producer_cell *cell,uint32_t phase) {
    Boolean original_state=0,current_state=0;
    int restore_pending=0;
    @try {
        OSStatus status=SecKeychainGetUserInteractionAllowed(&original_state);
        if(status!=errSecSuccess || (original_state!=0 && original_state!=1)) {failed(cell);return;}
        restore_pending=1; // arm BEFORE dispatch, including an ambiguous Set
        status=SecKeychainSetUserInteractionAllowed(false);
        if(status!=errSecSuccess) {failed(cell);return;}
        status=SecKeychainGetUserInteractionAllowed(&current_state);
        if(status!=errSecSuccess || current_state!=0) {failed(cell);return;}
        switch(phase) {
            case 3: {
                SecIdentityRef identity=NULL;
                status=SecIdentityCreateWithCertificate(NULL,(SecCertificateRef)cell->values[1],&identity);
                cell->values[2]=identity;break;
            }
            case 4: {
                SecCertificateRef certificate=NULL;
                status=SecIdentityCopyCertificate((SecIdentityRef)cell->values[2],&certificate);
                cell->values[3]=certificate;break;
            }
            case 6: {
                SecKeyRef key=NULL;
                status=SecIdentityCopyPrivateKey((SecIdentityRef)cell->values[2],&key);
                cell->values[5]=key;break;
            }
            case 7:cell->values[6]=SecKeyCopyPublicKey((SecKeyRef)cell->values[5]);break;
            case 11: {
                if(SecKeyGetBlockSize((SecKeyRef)cell->values[5])!=MRK_INSTALL_PRODUCER_RSA_BITS/8
                    || !SecKeyIsAlgorithmSupported((SecKeyRef)cell->values[5],kSecKeyOperationTypeSign,
                        kSecKeyAlgorithmRSASignatureMessagePKCS1v15SHA256)) {failed(cell);break;}
                CFErrorRef error=NULL;
                CFDataRef signature=SecKeyCreateSignature((SecKeyRef)cell->values[5],
                    kSecKeyAlgorithmRSASignatureMessagePKCS1v15SHA256,(CFDataRef)cell->values[10],&error);
                cell->values[11]=signature;cell->values[12]=error;
                if(error) failed(cell);break;
            }
            default:failed(cell);break;
        }
        if(status!=errSecSuccess) failed(cell);
    } @catch (...) {unknown(cell);}
    @finally {
        if(restore_pending) {
            @try {
                OSStatus status=SecKeychainSetUserInteractionAllowed(original_state);
                Boolean actual=0;
                OSStatus observed=SecKeychainGetUserInteractionAllowed(&actual);
                if(status!=errSecSuccess || observed!=errSecSuccess || actual!=original_state) unknown(cell);
            } @catch (...) {unknown(cell);}
        }
    }
}
static int sign_step(producer_cell *cell,uint32_t phase,mrk_install_producer_report *out) {
    if(!sign_role(cell->report.reserved) || cell->report.failed || cell->report.unknown || phase<1
        || phase>MRK_INSTALL_PRODUCER_SIGN_STEPS || phase!=cell->report.phase+1) return 0;
    unsigned slot=sign_slot(phase),error_slot=phase==9?9:phase==11?12:MRK_INSTALL_PRODUCER_SLOTS;
    if(slot>=MRK_INSTALL_PRODUCER_SIGN_SLOTS || cell->values[slot] || cell->report.states[slot]) return 0;
    if(error_slot<MRK_INSTALL_PRODUCER_SLOTS && (cell->values[error_slot] || cell->report.states[error_slot])) return 0;
    cell->report.phase=phase;cell->report.calls++;
    cell->report.states[slot]=1;
    if(error_slot<MRK_INSTALL_PRODUCER_SLOTS) cell->report.states[error_slot]=1;
    @try {
        switch(phase) {
            case 1:cell->values[0]=CFDataCreate(NULL,mrk_install_producer_leaf_der,sizeof(mrk_install_producer_leaf_der));break;
            case 2:cell->values[1]=SecCertificateCreateWithData(NULL,(CFDataRef)cell->values[0]);break;
            case 3:case 4:case 6:case 7:case 11:sign_keychain_phase(cell,phase);break;
            case 5:cell->values[4]=SecCertificateCopyData((SecCertificateRef)cell->values[3]);break;
            case 8:cell->values[7]=SecKeyCopyAttributes((SecKeyRef)cell->values[6]);break;
            case 9: {
                // Only the PUBLIC key can be exported; private attributes/data
                // and external private representations are never requested.
                CFErrorRef error=NULL;
                CFDataRef key=SecKeyCopyExternalRepresentation((SecKeyRef)cell->values[6],&error);
                cell->values[8]=key;cell->values[9]=error;
                if(error) failed(cell);break;
            }
            case 10:cell->values[10]=CFDataCreate(NULL,cell->message,cell->message_size);break;
            case 12: {
                CFErrorRef error=NULL;
                Boolean verified=SecKeyVerifySignature((SecKeyRef)cell->values[6],
                    kSecKeyAlgorithmRSASignatureMessagePKCS1v15SHA256,(CFDataRef)cell->values[10],
                    (CFDataRef)cell->values[11],&error);
                cell->values[13]=error;
                if(!verified || error) failed(cell);break;
            }
            default:failed(cell);break;
        }
        if(!cell->report.unknown) {
            received(cell,slot,phase!=12);
            if(error_slot<MRK_INSTALL_PRODUCER_SLOTS) received(cell,error_slot,0);
            if(!cell->report.failed && phase==5
                && !data_equal(cell->values[4],mrk_install_producer_leaf_der,sizeof(mrk_install_producer_leaf_der))) failed(cell);
            if(!cell->report.failed && phase==8 && !key_attributes(cell)) failed(cell);
            if(!cell->report.failed && phase==9) {
                CFDataRef key=(CFDataRef)cell->values[8];
                if(CFGetTypeID(key)!=CFDataGetTypeID() || CFDataGetLength(key)<=0 || CFDataGetLength(key)>16384
                    || !sha256_matches(CFDataGetBytePtr(key),(size_t)CFDataGetLength(key),mrk_install_producer_public_key_pkcs1_sha256)) failed(cell);
            }
            if(!cell->report.failed && phase==11) {
                CFTypeRef value=cell->values[11];
                if(CFGetTypeID(value)!=CFDataGetTypeID()
                    || CFDataGetLength((CFDataRef)value)!=MRK_INSTALL_PRODUCER_RSA_BITS/8) failed(cell);
                else {
                    cell->signature_size=MRK_INSTALL_PRODUCER_RSA_BITS/8;
                    memcpy(cell->signature,CFDataGetBytePtr((CFDataRef)value),cell->signature_size);
                }
            }
            cell->report.returned++;
            if(phase==MRK_INSTALL_PRODUCER_SIGN_STEPS && !cell->report.failed) cell->report.matched=1;
        }
    } @catch (...) {unknown(cell);}
    *out=cell->report;return 1;
}
#endif
#endif

int mrk_install_producer_source(mrk_install_producer_signer *out) {
    if(!out) return 0;memset(out,0,sizeof(*out));
#if MRK_INSTALL_PRODUCER_CONFIGURED
    if(!source_selected()) return 0;
    out->version=1;out->rsa_bits=MRK_INSTALL_PRODUCER_RSA_BITS;
    memcpy(out->team,mrk_install_producer_team,10);memcpy(out->leaf_sha1,mrk_install_producer_leaf_sha1,20);
    memcpy(out->leaf_sha256,mrk_install_producer_leaf_sha256,32);
    memcpy(out->public_key_pkcs1_sha256,mrk_install_producer_public_key_pkcs1_sha256,32);return 1;
#else
    return 0;
#endif
}
int mrk_install_producer_source_leaf_matches(const uint8_t *der,size_t size) {
#if MRK_INSTALL_PRODUCER_CONFIGURED
    return der && size==sizeof(mrk_install_producer_leaf_der) && source_selected()
        && memcmp(der,mrk_install_producer_leaf_der,size)==0;
#else
    (void)der;(void)size;return 0;
#endif
}
void *mrk_install_producer_new(const uint8_t *descriptor,size_t size,const uint8_t *signature,size_t signature_size) {
#if MRK_INSTALL_PRODUCER_CONFIGURED
    if(!source_selected() || !descriptor || !signature || !size || size>MRK_INSTALL_PRODUCER_DESCRIPTOR_MAX
        || signature_size!=MRK_INSTALL_PRODUCER_RSA_BITS/8 || getuid()!=geteuid() || getgid()!=getegid()) return NULL;
    producer_cell *cell=calloc(1,sizeof(*cell));if(!cell) return NULL;
    cell->magic=MRK_PRODUCER_MAGIC;cell->thread=pthread_self();cell->process=getpid();cell->uid=getuid();cell->gid=getgid();
    cell->report.version=1;cell->message_size=sizeof(message_domain)+size;cell->signature_size=signature_size;
    memcpy(cell->message,message_domain,sizeof(message_domain));memcpy(cell->message+sizeof(message_domain),descriptor,size);
    memcpy(cell->signature,signature,signature_size);return cell;
#else
    (void)descriptor;(void)size;(void)signature;(void)signature_size;return NULL;
#endif
}
void *mrk_install_producer_code_new(uint32_t role,int outer,int code,const uint8_t *path,size_t size) {
#if MRK_INSTALL_PRODUCER_CONFIGURED
    if(!source_selected() || (role!=1 && role!=2) || !canonical_path(path,size,role) || outer<0 || code<0
        || getuid()!=geteuid() || getgid()!=getegid()) return NULL;
    char outer_path[MRK_INSTALL_PRODUCER_PATH_MAX]={0},code_path[MRK_INSTALL_PRODUCER_PATH_MAX]={0};
    memcpy(outer_path,path,size);
    int length=snprintf(code_path,sizeof(code_path),"%s%s",outer_path,code_suffix(role));
    struct stat outer_identity={0},code_identity={0};
    if(length<=0 || (size_t)length>=sizeof(code_path) || fstat(outer,&outer_identity)!=0 || fstat(code,&code_identity)!=0
        || !borrowed_directory(outer,outer_path,&outer_identity) || !borrowed_directory(code,code_path,&code_identity)) return NULL;
    producer_cell *cell=calloc(1,sizeof(*cell));if(!cell) return NULL;
    cell->magic=MRK_PRODUCER_MAGIC;cell->thread=pthread_self();cell->process=getpid();cell->uid=getuid();cell->gid=getgid();
    cell->report.version=1;cell->report.reserved=role;cell->outer_fd=outer;cell->code_fd=code;
    cell->outer_identity=outer_identity;cell->code_identity=code_identity;
    memcpy(cell->outer_path,outer_path,sizeof(outer_path));memcpy(cell->code_path,code_path,sizeof(code_path));
    if(!code_originals(cell)) {cell->magic=0;free(cell);return NULL;}
    return cell;
#else
    (void)role;(void)outer;(void)code;(void)path;(void)size;return NULL;
#endif
}
void *mrk_remove_producer_new(const uint8_t *descriptor,size_t size,const uint8_t *signature,size_t signature_size) {
#if MRK_INSTALL_PRODUCER_CONFIGURED
    if(!source_selected() || !descriptor || !signature || !size || size>MRK_REMOVE_PRODUCER_DESCRIPTOR_MAX
        || signature_size!=MRK_INSTALL_PRODUCER_RSA_BITS/8 || getuid()!=geteuid() || getgid()!=getegid()) return NULL;
    producer_cell *cell=calloc(1,sizeof(*cell));if(!cell) return NULL;
    cell->magic=MRK_PRODUCER_MAGIC;cell->thread=pthread_self();cell->process=getpid();cell->uid=getuid();cell->gid=getgid();
    cell->report.version=1;cell->report.reserved=4;cell->message_size=sizeof(remove_message_domain)+size;cell->signature_size=signature_size;
    memcpy(cell->message,remove_message_domain,sizeof(remove_message_domain));memcpy(cell->message+sizeof(remove_message_domain),descriptor,size);
    memcpy(cell->signature,signature,signature_size);return cell;
#else
    (void)descriptor;(void)size;(void)signature;(void)signature_size;return NULL;
#endif
}
void *mrk_remove_producer_code_new(int directory,int program,const uint8_t *path,size_t size) {
#if MRK_INSTALL_PRODUCER_CONFIGURED
    if(!source_selected() || !canonical_path(path,size,5) || directory<0 || program<0
        || getuid()!=geteuid() || getgid()!=getegid()) return NULL;
    char outer_path[MRK_INSTALL_PRODUCER_PATH_MAX]={0},code_path[MRK_INSTALL_PRODUCER_PATH_MAX]={0};
    memcpy(outer_path,path,size);int length=snprintf(code_path,sizeof(code_path),"%s/mrk-macos-remove",outer_path);
    struct stat outer_identity={0},code_identity={0};
    if(length<=0 || (size_t)length>=sizeof(code_path) || fstat(directory,&outer_identity)!=0 || fstat(program,&code_identity)!=0
        || !borrowed_remove(directory,outer_path,&outer_identity,1) || !borrowed_remove(program,code_path,&code_identity,0)) return NULL;
    producer_cell *cell=calloc(1,sizeof(*cell));if(!cell) return NULL;
    cell->magic=MRK_PRODUCER_MAGIC;cell->thread=pthread_self();cell->process=getpid();cell->uid=getuid();cell->gid=getgid();
    cell->report.version=1;cell->report.reserved=5;cell->outer_fd=directory;cell->code_fd=program;
    cell->outer_identity=outer_identity;cell->code_identity=code_identity;
    memcpy(cell->outer_path,outer_path,sizeof(outer_path));memcpy(cell->code_path,code_path,sizeof(code_path));
    if(!code_originals(cell)){cell->magic=0;free(cell);return NULL;}return cell;
#else
    (void)directory;(void)program;(void)path;(void)size;return NULL;
#endif
}
int mrk_install_producer_step(void *raw,uint32_t phase,mrk_install_producer_report *out) {
#if MRK_INSTALL_PRODUCER_CONFIGURED
    producer_cell *cell=raw;
    if(!original(cell) || !out) return 0;
#if MRK_INSTALL_PRODUCER_SIGNING
    if(sign_role(cell->report.reserved)) return sign_step(cell,phase,out);
#endif
    if(code_role(cell->report.reserved)) return code_step(cell,phase,out);
    if(cell->report.reserved!=0 && cell->report.reserved!=4) return 0;
    if(cell->report.failed || cell->report.unknown || phase<1
        || phase>MRK_INSTALL_PRODUCER_STEPS || phase!=cell->report.phase+1) return 0;
    unsigned slot=phase_slot(phase);
    if(slot<MRK_INSTALL_PRODUCER_SLOTS && (cell->values[slot] || cell->report.states[slot])) return 0;
    if(phase==9 && (cell->values[9] || cell->report.states[9])) return 0;
    cell->report.phase=phase;cell->report.calls++;
    if(slot<MRK_INSTALL_PRODUCER_SLOTS) cell->report.states[slot]=1;
    if(phase==9) cell->report.states[9]=1;
    @try {
        OSStatus status=errSecSuccess;
        switch(phase) {
            case 1:cell->values[0]=CFDataCreate(NULL,mrk_install_producer_leaf_der,sizeof(mrk_install_producer_leaf_der));break;
            case 2:cell->values[1]=CFDataCreate(NULL,mrk_install_producer_issuer_der,sizeof(mrk_install_producer_issuer_der));break;
            case 3:cell->values[2]=CFDataCreate(NULL,mrk_install_producer_root_der,sizeof(mrk_install_producer_root_der));break;
            case 4:case 5:case 6:
                cell->values[slot]=SecCertificateCreateWithData(NULL,(CFDataRef)cell->values[phase-4]);break;
            case 7:cell->values[6]=SecCertificateCopyKey((SecCertificateRef)cell->values[3]);break;
            case 8:cell->values[7]=SecKeyCopyAttributes((SecKeyRef)cell->values[6]);break;
            case 9: {
                CFErrorRef error=NULL;
                CFDataRef key=SecKeyCopyExternalRepresentation((SecKeyRef)cell->values[6],&error);
                cell->values[8]=key;cell->values[9]=error;
                received(cell,9,0);if(cell->values[9]) failed(cell);break;
            }
            case 10:cell->values[10]=SecPolicyCreateBasicX509();break;
            case 11:cell->values[11]=SecPolicyCreateWithProperties(kSecPolicyAppleCodeSigning,NULL);break;
            case 12:cell->values[12]=SecPolicyCreateRevocation(kSecRevocationUseAnyAvailableMethod|kSecRevocationNetworkAccessDisabled);break;
            case 13: {
                const void *values[]={cell->values[3],cell->values[4]};
                cell->values[13]=CFArrayCreate(NULL,values,2,&kCFTypeArrayCallBacks);break;
            }
            case 14: {
                const void *values[]={cell->values[10],cell->values[11],cell->values[12]};
                cell->values[14]=CFArrayCreate(NULL,values,3,&kCFTypeArrayCallBacks);break;
            }
            case 15: {
                const void *values[]={cell->values[5]};cell->values[15]=CFArrayCreate(NULL,values,1,&kCFTypeArrayCallBacks);break;
            }
            case 16: {
                SecTrustRef trust=NULL;
                status=SecTrustCreateWithCertificates(cell->values[13],cell->values[14],&trust);
                cell->values[16]=trust;break;
            }
            case 17:status=SecTrustSetAnchorCertificates((SecTrustRef)cell->values[16],(CFArrayRef)cell->values[15]);break;
            case 18:status=SecTrustSetAnchorCertificatesOnly((SecTrustRef)cell->values[16],true);break;
            case 19:status=SecTrustSetNetworkFetchAllowed((SecTrustRef)cell->values[16],false);break;
            case 20:cell->values[17]=CFDateCreate(NULL,CFAbsoluteTimeGetCurrent());break;
            case 21:status=SecTrustSetVerifyDate((SecTrustRef)cell->values[16],(CFDateRef)cell->values[17]);break;
            case 22: {
                CFErrorRef error=NULL;
                Boolean evaluated=SecTrustEvaluateWithError((SecTrustRef)cell->values[16],&error);
                cell->values[18]=error;
                if(!evaluated || cell->values[18]) failed(cell);break;
            }
            case 23:cell->values[19]=SecTrustCopyCertificateChain((SecTrustRef)cell->values[16]);break;
            case 24:case 25:case 26: {
                CFArrayRef chain=(CFArrayRef)cell->values[19];
                if(!chain || CFGetTypeID(chain)!=CFArrayGetTypeID() || CFArrayGetCount(chain)!=3) { failed(cell);break; }
                CFTypeRef certificate=CFArrayGetValueAtIndex(chain,phase-24);
                if(!certificate || CFGetTypeID(certificate)!=SecCertificateGetTypeID()) { failed(cell);break; }
                cell->values[slot]=SecCertificateCopyData((SecCertificateRef)certificate);break;
            }
            case 27:cell->values[23]=CFDataCreate(NULL,cell->message,cell->message_size);break;
            case 28:cell->values[24]=CFDataCreate(NULL,cell->signature,cell->signature_size);break;
            case 29: {
                CFErrorRef error=NULL;
                Boolean verified=SecKeyVerifySignature((SecKeyRef)cell->values[6],kSecKeyAlgorithmRSASignatureMessagePKCS1v15SHA256,
                    (CFDataRef)cell->values[23],(CFDataRef)cell->values[24],&error);
                cell->values[25]=error;
                if(!verified || cell->values[25]) failed(cell);break;
            }
            default:failed(cell);break;
        }
        if(slot<MRK_INSTALL_PRODUCER_SLOTS) received(cell,slot,phase!=22 && phase!=29);
        if(status!=errSecSuccess) failed(cell);
        if(!cell->report.failed && phase==8 && !key_attributes(cell)) failed(cell);
        if(!cell->report.failed && phase==9) {
            CFDataRef key=(CFDataRef)cell->values[8];
            if(CFGetTypeID(key)!=CFDataGetTypeID() || CFDataGetLength(key)<=0 || CFDataGetLength(key)>16384
                || !sha256_matches(CFDataGetBytePtr(key),(size_t)CFDataGetLength(key),mrk_install_producer_public_key_pkcs1_sha256)) failed(cell);
        }
        if(!cell->report.failed && phase==24 && !data_equal(cell->values[20],mrk_install_producer_leaf_der,sizeof(mrk_install_producer_leaf_der))) failed(cell);
        if(!cell->report.failed && phase==25 && !data_equal(cell->values[21],mrk_install_producer_issuer_der,sizeof(mrk_install_producer_issuer_der))) failed(cell);
        if(!cell->report.failed && phase==26 && !data_equal(cell->values[22],mrk_install_producer_root_der,sizeof(mrk_install_producer_root_der))) failed(cell);
        cell->report.returned++;
        if(phase==29 && !cell->report.failed) cell->report.matched=1;
    } @catch (...) { unknown(cell); }
    *out=cell->report;return 1;
#else
    (void)raw;(void)phase;(void)out;return 0;
#endif
}
int mrk_install_producer_release(void *raw,uint32_t slot,mrk_install_producer_report *out) {
#if MRK_INSTALL_PRODUCER_CONFIGURED
    producer_cell *cell=raw;
    if(!original(cell) || !out || slot>=MRK_INSTALL_PRODUCER_SLOTS || cell->report.unknown
        || cell->report.calls!=cell->report.returned || cell->report.states[slot]!=2 || !cell->values[slot]) return 0;
    cell->report.phase=MRK_INSTALL_PRODUCER_RELEASE+slot;cell->report.states[slot]=3;cell->report.calls++;
    @try {
        CFRelease(cell->values[slot]);cell->values[slot]=NULL;cell->report.states[slot]=4;cell->report.returned++;
    } @catch (...) { unknown(cell); }
    *out=cell->report;return 1;
#else
    (void)raw;(void)slot;(void)out;return 0;
#endif
}
int mrk_install_producer_retire(void *raw) {
#if MRK_INSTALL_PRODUCER_CONFIGURED
    producer_cell *cell=raw;
    if(!original(cell) || cell->report.unknown || cell->report.calls!=cell->report.returned) return 0;
    for(unsigned i=0;i<MRK_INSTALL_PRODUCER_SLOTS;i++)
        if(cell->values[i] || (cell->report.states[i]!=0 && cell->report.states[i]!=4)) return 0;
    cell->magic=0;free(cell);return 1;
#else
    (void)raw;return 0;
#endif
}
#if MRK_INSTALL_PRODUCER_SIGNING
void *mrk_install_producer_sign_new(const uint8_t *descriptor,size_t size) {
#if MRK_INSTALL_PRODUCER_CONFIGURED
    if(!source_selected() || !descriptor || !size || size>MRK_INSTALL_PRODUCER_DESCRIPTOR_MAX
        || getuid()!=geteuid() || getgid()!=getegid()) return NULL;
    producer_cell *cell=calloc(1,sizeof(*cell));if(!cell) return NULL;
    cell->magic=MRK_PRODUCER_MAGIC;cell->thread=pthread_self();cell->process=getpid();cell->uid=getuid();cell->gid=getgid();
    cell->report.version=1;cell->report.reserved=3;cell->message_size=sizeof(message_domain)+size;
    memcpy(cell->message,message_domain,sizeof(message_domain));memcpy(cell->message+sizeof(message_domain),descriptor,size);
    return cell;
#else
    (void)descriptor;(void)size;return NULL;
#endif
}
void *mrk_remove_producer_sign_new(const uint8_t *descriptor,size_t size) {
#if MRK_INSTALL_PRODUCER_CONFIGURED
    if(!source_selected() || !descriptor || !size || size>MRK_REMOVE_PRODUCER_DESCRIPTOR_MAX
        || getuid()!=geteuid() || getgid()!=getegid()) return NULL;
    producer_cell *cell=calloc(1,sizeof(*cell));if(!cell) return NULL;
    cell->magic=MRK_PRODUCER_MAGIC;cell->thread=pthread_self();cell->process=getpid();cell->uid=getuid();cell->gid=getgid();
    cell->report.version=1;cell->report.reserved=6;cell->message_size=sizeof(remove_message_domain)+size;
    memcpy(cell->message,remove_message_domain,sizeof(remove_message_domain));memcpy(cell->message+sizeof(remove_message_domain),descriptor,size);
    return cell;
#else
    (void)descriptor;(void)size;return NULL;
#endif
}
int mrk_install_producer_sign_copy(void *raw,uint8_t *out,size_t capacity,size_t *size) {
#if MRK_INSTALL_PRODUCER_CONFIGURED
    producer_cell *cell=raw;
    if(!original(cell) || !out || !size || capacity!=sizeof(cell->signature) || !sign_role(cell->report.reserved)
        || cell->signature_copied || cell->report.failed || cell->report.unknown || cell->report.matched!=1
        || cell->report.phase!=MRK_INSTALL_PRODUCER_SIGN_STEPS || cell->report.calls!=cell->report.returned
        || cell->signature_size!=MRK_INSTALL_PRODUCER_RSA_BITS/8) return 0;
    cell->signature_copied=1;
    memcpy(out,cell->signature,cell->signature_size);*size=cell->signature_size;return 1;
#else
    (void)raw;(void)out;(void)capacity;(void)size;return 0;
#endif
}
#endif
