//! Bounded expected-input/hash/latch DATA. Nothing here authenticates a supplier,
//! opens a file, selects a destination or produces native acquisition finality.

use serde::Deserialize;
use sha2::{Digest, Sha256};
use crate::runtime::windows_version::{MANIFEST_BYTES, TARGET};

pub(crate) const INPUTS: usize = 54;
pub(crate) const RUNTIME_INPUTS: usize = 47;
pub(crate) const MANIFEST: usize = 7;
const HELPER: usize = 47;
const CONTROLS: [usize; 2] = [52, 53];
const CONTROL_LIMITS: [u64; 2] = [16 * 1024, 1024 * 1024];
const FILE_BYTES: u64 = 512 * 1024 * 1024;
const PAYLOAD_BYTES: u64 = 1024 * 1024 * 1024;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PolicyError { Format, Binding, Bounds, Count, Size, Eof, Hash, State, Manifest, Finality }
impl PolicyError {
    pub(crate) fn label(self) -> &'static str {
        match self {
            Self::Format => "format", Self::Binding => "binding", Self::Bounds => "bounds",
            Self::Count => "count", Self::Size => "size", Self::Eof => "eof", Self::Hash => "hash",
            Self::State => "state", Self::Manifest => "manifest", Self::Finality => "finality",
        }
    }
}

fn digest_text(value: &str) -> bool {
    value.len() == 64 && value.bytes().all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
}
fn hex(bytes: &[u8]) -> String {
    const DIGITS: &[u8; 16] = b"0123456789abcdef";
    let mut value = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        value.push(DIGITS[(byte >> 4) as usize] as char);
        value.push(DIGITS[(byte & 15) as usize] as char);
    }
    value
}

/// Immutable DATA, not an authenticated profile or an installation capability.
/// The fixed bridge must embed rows generated by the existing Python DATA3
/// validator and bind that bridge plus its actual inputs in the packaging roster.
/// Order is runtime47, publisher, shell, prerequisite, notices2, controls2;
/// it is NOT the lexicographically sorted DATA3 inventory order.
pub struct ExpectedInputData {
    manifest: String,
    helper: String,
    // Set only after exact PROFILE hash/schema/row decoding. Compiled acquisition
    // also requires independent compile pins; retained maintenance authenticates
    // actual protected originals. A DATA-only constructor cannot select an image.
    image: Option<String>,
    sizes: [u64; INPUTS],
    hashes: [String; INPUTS],
    runtime_bytes: u64,
}
impl ExpectedInputData {
    pub fn new(manifest: &str, helper: &str, sizes: [u64; INPUTS], hashes: [String; INPUTS])
        -> Result<Self, PolicyError> {
        if !digest_text(manifest) || !digest_text(helper) || hashes.iter().any(|h| !digest_text(h)) {
            return Err(PolicyError::Format);
        }
        if hashes[MANIFEST] != manifest || hashes[HELPER] != helper { return Err(PolicyError::Binding); }
        if sizes.iter().any(|n| *n == 0 || *n > FILE_BYTES) || sizes[MANIFEST] > MANIFEST_BYTES
            || CONTROLS.iter().zip(CONTROL_LIMITS).any(|(i, limit)| sizes[*i] > limit) {
            return Err(PolicyError::Bounds);
        }
        let sum = |rows: &[u64]| rows.iter().try_fold(0u64, |total, n| total.checked_add(*n))
            .ok_or(PolicyError::Count);
        let runtime_bytes = sum(&sizes[..RUNTIME_INPUTS])?;
        // Preserve the downstream publisher's two complete runtime reads. The
        // acquisition's separate book budgets do not make a larger runtime valid.
        if !runtime_bytes.checked_mul(2).is_some_and(|n| n <= PAYLOAD_BYTES)
            || sum(&sizes[..CONTROLS[0]])? > PAYLOAD_BYTES {
            return Err(PolicyError::Bounds);
        }
        // Native InputAcquisition::new still enforces its narrower per-role
        // shell/publisher/notice limits. This is not a second DATA3 validator.
        Ok(Self { manifest: manifest.to_owned(), helper: helper.to_owned(), image: None, sizes, hashes, runtime_bytes })
    }
    pub(crate) fn bind_compiled(&self, manifest: &str) -> Result<(), PolicyError> {
        if self.manifest == manifest && self.hashes[MANIFEST] == manifest { Ok(()) }
        else { Err(PolicyError::Binding) }
    }
    pub(crate) fn manifest(&self) -> &str { &self.manifest }
    pub(crate) fn helper(&self) -> &str { &self.helper }
    pub(crate) fn image(&self) -> Result<&str, PolicyError> {
        self.image.as_deref().ok_or(PolicyError::Binding)
    }
    pub(crate) fn sizes(&self) -> [u64; INPUTS] { self.sizes }
    pub(crate) fn selection_hashes(&self) -> Result<[String; INPUTS], PolicyError> {
        self.image()?; Ok(self.hashes.clone())
    }
    pub(crate) fn runtime_bytes(&self) -> u64 { self.runtime_bytes }
    /// DATA-only fixed row49 hash. A decoded image binding is required; this
    /// getter neither admits the file nor creates an acquisition/runtime receipt.
    pub(crate) fn offline_prerequisite_sha256(&self) -> Result<[u8; 32], PolicyError> {
        self.image()?;
        let text = self.hashes.get(49).ok_or(PolicyError::State)?;
        if !digest_text(text) { return Err(PolicyError::Format); }
        let mut hash = [0u8; 32];
        for (index, byte) in hash.iter_mut().enumerate() {
            let pair = text.get(index * 2..index * 2 + 2).ok_or(PolicyError::Format)?;
            *byte = u8::from_str_radix(pair, 16).map_err(|_| PolicyError::Format)?;
        }
        Ok(hash)
    }
    pub(crate) fn matches(&self, index: usize, size: u64, hash: &str) -> bool {
        self.sizes.get(index) == Some(&size) && self.hashes.get(index).is_some_and(|h| h == hash)
    }
    pub(crate) fn stream(&self, index: usize) -> Result<StreamProof, PolicyError> {
        let size = *self.sizes.get(index).ok_or(PolicyError::State)?;
        let hash = self.hashes.get(index).ok_or(PolicyError::State)?.clone();
        Ok(StreamProof { size, hash, count: 0, hasher: Sha256::new(), eof: false, first: None })
    }
    pub(crate) fn verify_control(&self, control: usize, original: &[u8]) -> Result<(), PolicyError> {
        let index = *CONTROLS.get(control).ok_or(PolicyError::State)?;
        if original.len() as u64 != self.sizes[index] { return Err(PolicyError::Size); }
        if hex(&Sha256::digest(original)) != self.hashes[index] { return Err(PolicyError::Hash); }
        // Only admit_once's actual original caches/EOF may supply these bytes.
        // This hash result on its own is neither EOF nor native admission.
        Ok(())
    }
}

pub(crate) const PROFILE_BYTES: usize = 8192;

/// Independent compile inputs, not values read back out of the profile itself.
/// Only the isolated compiled consumer constructs these in a production path.
pub(crate) struct ProfileBindings<'a> {
    pub(crate) profile_sha256: &'a str,
    pub(crate) source_commit: &'a str,
    pub(crate) target: &'a str,
    pub(crate) core_version: &'a str,
    pub(crate) manifest_sha256: &'a str,
    pub(crate) protocol_sha256: &'a str,
}

// A bounded transport DTO, not another DATA3/supplier/path validator. The Python
// generator reuses _inputs; the actual driver still validates the original runtime
// manifest/roster. Serde's struct decoder refuses duplicate and unknown fields.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Profile {
    schema_version: u32,
    purpose: String,
    input_assertions: String,
    source_commit: String,
    target: String,
    core_version: String,
    runtime_manifest_sha256: String,
    protocol_sha256: String,
    publisher_sha256: String,
    admission_sha256: String,
    inventory_sha256: String,
    inputs: Vec<ProfileRow>,
}
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct ProfileRow { size: u64, sha256: String }

fn profile_pin(value: &str, length: usize) -> bool {
    value.len() == length && value.bytes().any(|b| b != b'0')
        && value.bytes().all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
}

/// Hash-before-JSON for the existing single PROFILE transport. A retained
/// protected profile is DATA, not a replacement for independent compile pins.
fn profile_transport(raw: &[u8], image: &str) -> Result<Profile, PolicyError> {
    if raw.is_empty() || raw.len() > PROFILE_BYTES { return Err(PolicyError::Bounds); }
    if !profile_pin(image, 64) { return Err(PolicyError::Format); }
    if hex(&Sha256::digest(raw)) != image { return Err(PolicyError::Hash); }
    if !raw.iter().all(|b| (b' '..=b'~').contains(b)) { return Err(PolicyError::Format); }
    let value: Profile = serde_json::from_slice(raw).map_err(|_| PolicyError::Format)?;
    if value.schema_version != 1 || value.purpose != "windows-installer-acquisition-profile"
        || value.input_assertions != "supplied-not-observed" { return Err(PolicyError::Format); }
    if !profile_pin(&value.source_commit, 40)
        || [&value.runtime_manifest_sha256, &value.protocol_sha256, &value.publisher_sha256,
            &value.admission_sha256, &value.inventory_sha256].iter().any(|s| !profile_pin(s, 64)) {
        return Err(PolicyError::Format);
    }
    Ok(value)
}
fn profile_rows(value: Profile, image: &str) -> Result<ExpectedInputData, PolicyError> {
    let rows: [ProfileRow; INPUTS] = value.inputs.try_into().map_err(|_| PolicyError::Count)?;
    if rows.iter().any(|r| !profile_pin(&r.sha256, 64)) { return Err(PolicyError::Format); }
    if rows[CONTROLS[0]].sha256 != value.admission_sha256
        || rows[CONTROLS[1]].sha256 != value.inventory_sha256 { return Err(PolicyError::Binding); }
    let sizes = std::array::from_fn(|i| rows[i].size);
    // Same constructor owns row7=D,row47=H, exact54 and bounded two-read capacity.
    let mut data = ExpectedInputData::new(&value.runtime_manifest_sha256, &value.publisher_sha256,
        sizes, rows.map(|r| r.sha256))?;
    data.image = Some(image.to_owned());
    Ok(data)
}
pub(crate) fn decode_profile(raw: &[u8], expected: &ProfileBindings<'_>)
    -> Result<ExpectedInputData, PolicyError> {
    if raw.is_empty() || raw.len() > PROFILE_BYTES { return Err(PolicyError::Bounds); }
    if !profile_pin(expected.profile_sha256, 64) || !profile_pin(expected.source_commit, 40)
        || !profile_pin(expected.manifest_sha256, 64) || !profile_pin(expected.protocol_sha256, 64) {
        return Err(PolicyError::Format);
    }
    let value = profile_transport(raw, expected.profile_sha256)?;
    if expected.target != TARGET || value.source_commit != expected.source_commit
        || value.target != expected.target || value.core_version != expected.core_version
        || value.runtime_manifest_sha256 != expected.manifest_sha256
        || value.protocol_sha256 != expected.protocol_sha256 { return Err(PolicyError::Binding); }
    profile_rows(value, expected.profile_sha256)
}

/// Decoded existing-schema DATA only. Native selection must have read the exact
/// protected profile original and must bind these bytes back to that SAME owner.
/// Old images need not match the current program's source commit/core version:
/// this function cannot admit a new supplier, copied activation or native handle.
pub(crate) struct RetainedProfileData {
    pub(crate) inputs: ExpectedInputData,
    pub(crate) core_version: String,
}
pub(crate) fn decode_retained_profile(raw: &[u8], observed_image: &str)
    -> Result<RetainedProfileData, PolicyError> {
    let value = profile_transport(raw, observed_image)?;
    if value.target != TARGET { return Err(PolicyError::Binding); }
    if value.core_version.is_empty() || value.core_version.len() > 64
        || !value.core_version.bytes().all(|b| b.is_ascii_alphanumeric() || b".-_+".contains(&b)) {
        return Err(PolicyError::Format);
    }
    let core_version = value.core_version.clone();
    let inputs = profile_rows(value, observed_image)?;
    Ok(RetainedProfileData { inputs, core_version })
}

/// An actual source stream and its independent actual readback use separate
/// instances. A size match cannot invent EOF; any refused observation is final.
pub(crate) struct StreamProof {
    size: u64, hash: String, count: u64, hasher: Sha256, eof: bool, first: Option<PolicyError>,
}
impl StreamProof {
    pub(crate) fn observe(&mut self, bytes: &[u8]) -> Result<(), PolicyError> {
        if let Some(first) = self.first { return Err(first); }
        let result = if self.eof { Err(PolicyError::State) }
        else if bytes.is_empty() { self.eof = true; Ok(()) }
        else {
            match self.count.checked_add(bytes.len() as u64) {
                None => Err(PolicyError::Count),
                Some(count) if count > self.size => Err(PolicyError::Size),
                Some(count) => { self.hasher.update(bytes); self.count = count; Ok(()) },
            }
        };
        if let Err(error) = result { self.first = Some(error); }
        result
    }
    pub(crate) fn verify(self) -> Result<(), PolicyError> {
        if let Some(first) = self.first { return Err(first); }
        if !self.eof { return Err(PolicyError::Eof); }
        if self.count != self.size { return Err(PolicyError::Size); }
        if hex(&self.hasher.finalize()) != self.hash { return Err(PolicyError::Hash); }
        Ok(())
    }
}

pub(crate) fn retain_manifest_chunk(cache: &mut Vec<u8>, bytes: &[u8]) -> Result<(), PolicyError> {
    if !cache.len().checked_add(bytes.len()).is_some_and(|n| n as u64 <= MANIFEST_BYTES) {
        return Err(PolicyError::Bounds);
    }
    cache.extend_from_slice(bytes); Ok(())
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum Phase {
    Admit, Controls, Create, StartCopy, SourceNext, SourceHash, SourceVerify, Decode,
    FinishCopy, ReadbackNext, ReadbackHash, ReadbackVerify, FinishReadback, Finish, Finality,
}
impl Phase {
    pub(crate) fn label(self) -> &'static str {
        match self {
            Self::Admit => "admit", Self::Controls => "controls", Self::Create => "create",
            Self::StartCopy => "start-copy", Self::SourceNext => "source-next", Self::SourceHash => "source-hash",
            Self::SourceVerify => "source-verify", Self::Decode => "manifest-decode", Self::FinishCopy => "finish-copy",
            Self::ReadbackNext => "readback-next", Self::ReadbackHash => "readback-hash",
            Self::ReadbackVerify => "readback-verify", Self::FinishReadback => "finish-readback",
            Self::Finish => "finish", Self::Finality => "finality",
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum Cause { Policy(PolicyError), Stopped, Unavailable, Unsafe, Bounds, State, Unknown }
impl Cause {
    pub(crate) fn label(self) -> &'static str {
        match self {
            Self::Policy(error) => error.label(), Self::Stopped => "stopped", Self::Unavailable => "native-unavailable",
            Self::Unsafe => "native-unsafe", Self::Bounds => "native-bounds", Self::State => "native-state",
            Self::Unknown => "native-unknown",
        }
    }
}
/// Closed first-return DATA. There are no paths, raw control bytes or handles.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Failure { pub(crate) phase: Phase, pub(crate) ordinal: Option<usize>, pub(crate) cause: Cause }
#[derive(Default)]
pub(crate) struct FailureLatch { first: Option<Failure> }
impl FailureLatch {
    pub(crate) fn after<T>(&mut self, phase: Phase, ordinal: Option<usize>, result: Result<T, Cause>, stop: bool)
        -> Result<T, Failure> {
        if let Some(first) = self.first { return Err(first); }
        // A step that already returned an error wins over STOP observed after
        // its return. Never replace it with a later phase or cleanup failure.
        let cause = match result {
            Err(cause) => cause,
            Ok(value) if !stop => return Ok(value),
            Ok(_) => Cause::Stopped,
        };
        let first = Failure { phase, ordinal, cause }; self.first = Some(first); Err(first)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    fn fixture() -> ExpectedInputData {
        let hash = hex(&Sha256::digest(b"x"));
        ExpectedInputData::new(&hash, &hash, [1; INPUTS], std::array::from_fn(|_| hash.clone())).unwrap()
    }
    #[test]
    fn fixed_bindings_and_downstream_two_read_budget_precede_native_work() {
        let input = fixture();
        assert!(input.bind_compiled(&input.manifest).is_ok());
        assert_eq!(input.bind_compiled(&"a".repeat(64)), Err(PolicyError::Binding));
        assert!(matches!(ExpectedInputData::new(&input.manifest, &"a".repeat(64), input.sizes, input.hashes.clone()), Err(PolicyError::Binding)));
        let mut hashes = input.hashes.clone(); hashes[MANIFEST] = "f".repeat(64);
        assert!(matches!(ExpectedInputData::new(&input.manifest, &input.helper, input.sizes, hashes), Err(PolicyError::Binding)));
        let mut sizes = input.sizes; sizes[0] = FILE_BYTES - (RUNTIME_INPUTS as u64 - 1);
        assert!(ExpectedInputData::new(&input.manifest, &input.helper, sizes, input.hashes.clone()).is_ok());
        sizes[0] += 1;
        assert!(matches!(ExpectedInputData::new(&input.manifest, &input.helper, sizes, input.hashes.clone()), Err(PolicyError::Bounds)));
        for (index, excess) in [(MANIFEST, MANIFEST_BYTES + 1), (52, CONTROL_LIMITS[0] + 1), (53, CONTROL_LIMITS[1] + 1)] {
            let mut sizes = input.sizes; sizes[index] = excess;
            assert!(matches!(ExpectedInputData::new(&input.manifest, &input.helper, sizes, input.hashes.clone()), Err(PolicyError::Bounds)));
        }
    }
    #[test]
    fn each_original_control_needs_its_own_size_and_hash() {
        let mut input = fixture(); input.hashes[53] = hex(&Sha256::digest(b"y"));
        assert_eq!(input.verify_control(0, b"x"), Ok(()));
        assert_eq!(input.verify_control(1, b"y"), Ok(()));
        assert_eq!(input.verify_control(0, b"y"), Err(PolicyError::Hash));
        assert_eq!(input.verify_control(1, b"x"), Err(PolicyError::Hash));
        assert_eq!(input.verify_control(1, b"yy"), Err(PolicyError::Size));
    }
    #[test]
    fn exact_size_is_not_eof_and_readback_cannot_reuse_the_source_hash() {
        let input = fixture();
        let mut source = input.stream(0).unwrap(); source.observe(b"x").unwrap();
        assert_eq!(source.verify(), Err(PolicyError::Eof));
        let mut source = input.stream(0).unwrap(); source.observe(b"x").unwrap(); source.observe(b"").unwrap();
        assert_eq!(source.verify(), Ok(()));
        let mut readback = input.stream(0).unwrap(); readback.observe(b"y").unwrap(); readback.observe(b"").unwrap();
        assert_eq!(readback.verify(), Err(PolicyError::Hash));
        let mut short = input.stream(0).unwrap(); short.observe(b"").unwrap();
        assert_eq!(short.verify(), Err(PolicyError::Size));
    }
    #[test]
    fn excess_overflow_and_post_eof_observations_are_absorbing() {
        let input = fixture(); let mut stream = input.stream(0).unwrap();
        assert_eq!(stream.observe(b"xx"), Err(PolicyError::Size));
        assert_eq!(stream.observe(b""), Err(PolicyError::Size));
        assert_eq!(stream.verify(), Err(PolicyError::Size));
        let mut stream = input.stream(0).unwrap(); stream.size = u64::MAX; stream.count = u64::MAX;
        assert_eq!(stream.observe(b"x"), Err(PolicyError::Count));
        assert_eq!(stream.verify(), Err(PolicyError::Count));
        let mut stream = input.stream(0).unwrap(); stream.observe(b"x").unwrap(); stream.observe(b"").unwrap();
        assert_eq!(stream.observe(b""), Err(PolicyError::State));
        assert_eq!(stream.verify(), Err(PolicyError::State));
    }
    #[test]
    fn returned_error_wins_over_post_step_stop_and_later_failures() {
        let mut latch = FailureLatch::default();
        let first = latch.after::<()>(Phase::SourceNext, Some(3), Err(Cause::Unsafe), true).unwrap_err();
        assert_eq!(first.cause, Cause::Unsafe);
        assert_eq!(latch.after(Phase::Finality, None, Err::<(), _>(Cause::Unknown), true), Err(first));
        let mut latch = FailureLatch::default();
        let stopped = latch.after(Phase::StartCopy, Some(4), Ok(()), true).unwrap_err();
        assert_eq!(stopped.cause, Cause::Stopped);
        assert_eq!(latch.after(Phase::Finish, None, Ok(()), false), Err(stopped));
        let mut latch = FailureLatch::default();
        assert!(latch.after(Phase::Finality, None, Ok(()), false).is_ok());
        assert_eq!(latch.after::<()>(Phase::Finality, None, Err(Cause::Policy(PolicyError::Finality)), true).unwrap_err().cause,
            Cause::Policy(PolicyError::Finality));
    }
    #[test]
    fn same_original_manifest_cache_is_bounded_without_truncation() {
        let mut cache = Vec::new(); let block = vec![b'x'; 64 * 1024];
        for _ in 0..MANIFEST_BYTES / block.len() as u64 { retain_manifest_chunk(&mut cache, &block).unwrap(); }
        assert_eq!(cache.len() as u64, MANIFEST_BYTES);
        assert_eq!(retain_manifest_chunk(&mut cache, b"x"), Err(PolicyError::Bounds));
        assert_eq!(cache.len() as u64, MANIFEST_BYTES);
    }

    fn profile_bindings(hash: &str) -> ProfileBindings<'_> {
        ProfileBindings {
            profile_sha256: hash, source_commit: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            target: TARGET, core_version: crate::runtime::CORE_VERSION,
            manifest_sha256: "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
            protocol_sha256: "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
        }
    }
    // Invented supplied DATA only. It does not pretend to be an original runtime
    // manifest, native input, admitted bridge image or qualification receipt.
    fn profile_value() -> serde_json::Value {
        let pins = profile_bindings("");
        let mut rows: Vec<_> = (0..INPUTS).map(|_| serde_json::json!({
            "size": 1, "sha256": hex(&Sha256::digest(b"x")),
        })).collect();
        rows[MANIFEST]["sha256"] = serde_json::json!(pins.manifest_sha256);
        rows[HELPER]["sha256"] = serde_json::json!("e".repeat(64));
        rows[52]["sha256"] = serde_json::json!(hex(&Sha256::digest(b"a")));
        rows[53]["sha256"] = serde_json::json!(hex(&Sha256::digest(b"i")));
        serde_json::json!({
            "schemaVersion": 1, "purpose": "windows-installer-acquisition-profile",
            "inputAssertions": "supplied-not-observed", "sourceCommit": pins.source_commit,
            "target": TARGET, "coreVersion": pins.core_version,
            "runtimeManifestSha256": pins.manifest_sha256, "protocolSha256": pins.protocol_sha256,
            "publisherSha256": "e".repeat(64), "admissionSha256": rows[52]["sha256"],
            "inventorySha256": rows[53]["sha256"], "inputs": rows,
        })
    }
    fn decode_value(value: &serde_json::Value) -> Result<ExpectedInputData, PolicyError> {
        let raw = serde_json::to_vec(value).unwrap();
        decode_profile(&raw, &profile_bindings(&hex(&Sha256::digest(&raw))))
    }
    #[test]
    fn fixed_profile_decodes_into_actual_constructor_and_distinct_control_order() {
        let value = profile_value();
        let decoded = decode_value(&value).unwrap();
        assert_eq!(decoded.runtime_bytes(), RUNTIME_INPUTS as u64);
        for i in 0..INPUTS {
            assert!(decoded.matches(i, 1, value["inputs"][i]["sha256"].as_str().unwrap()));
        }
        assert_eq!(decoded.verify_control(0, b"a"), Ok(()));
        assert_eq!(decoded.verify_control(1, b"i"), Ok(()));
        assert_eq!(decoded.verify_control(0, b"i"), Err(PolicyError::Hash));
        assert_eq!(decoded.verify_control(1, b"a"), Err(PolicyError::Hash));
    }
    #[test]
    fn unchanged_runtime_with_changed_shell_selects_a_distinct_profile_image() {
        let first = profile_value();
        let a = decode_value(&first).unwrap();
        let mut next = first;
        next["inputs"][48]["sha256"] = serde_json::json!("f".repeat(64));
        let b = decode_value(&next).unwrap();
        assert_eq!(a.manifest(), b.manifest());
        assert_ne!(a.image().unwrap(), b.image().unwrap());
        assert_eq!(a.image().unwrap(), hex(&Sha256::digest(serde_json::to_vec(&profile_value()).unwrap())));
        assert!(fixture().image().is_err()); // unbound DATA cannot select a retained image
    }
    #[test]
    fn profile_hash_is_checked_before_json_and_rehash_cannot_replace_compile_bindings() {
        let raw = serde_json::to_vec(&profile_value()).unwrap();
        let hash = hex(&Sha256::digest(&raw));
        assert!(matches!(decode_profile(b"not JSON", &profile_bindings(&hash)), Err(PolicyError::Hash)));
        let invalid_hash = hex(&Sha256::digest(b"not JSON"));
        assert!(matches!(decode_profile(b"not JSON", &profile_bindings(&invalid_hash)), Err(PolicyError::Format)));
        for (key, replacement) in [
            ("sourceCommit", "b".repeat(40)), ("target", "aarch64-pc-windows-msvc".to_owned()),
            ("coreVersion", "0.3.1".to_owned()), ("runtimeManifestSha256", "b".repeat(64)),
            ("protocolSha256", "b".repeat(64)), ("publisherSha256", "b".repeat(64)),
            ("admissionSha256", "b".repeat(64)), ("inventorySha256", "b".repeat(64)),
        ] {
            let mut value = profile_value(); value[key] = serde_json::json!(replacement);
            assert!(matches!(decode_value(&value), Err(PolicyError::Binding)), "{key}");
        }
        let mut pins = profile_bindings(&hash); pins.source_commit = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
        assert!(matches!(decode_profile(&raw, &pins), Err(PolicyError::Binding)));
        pins.source_commit = "0000000000000000000000000000000000000000";
        assert!(matches!(decode_profile(&raw, &pins), Err(PolicyError::Format)));
    }
    #[test]
    fn profile_shape_types_bounds_and_duplicate_fields_fail_closed() {
        let original = profile_value();
        let raw = serde_json::to_string(&original).unwrap();
        let duplicate = raw.replacen("\"schemaVersion\":1", "\"schemaVersion\":1,\"schemaVersion\":1", 1);
        let duplicate_row = raw.replacen("\"size\":1", "\"size\":1,\"size\":1", 1);
        for bytes in [duplicate.into_bytes(), duplicate_row.into_bytes(), [raw.as_bytes(), b"\n"].concat()] {
            let hash = hex(&Sha256::digest(&bytes));
            assert!(matches!(decode_profile(&bytes, &profile_bindings(&hash)), Err(PolicyError::Format)));
        }
        for row in [false, true] {
            let mut value = original.clone();
            if row { value["inputs"][0]["extra"] = serde_json::json!(1); }
            else { value["extra"] = serde_json::json!(1); }
            assert!(matches!(decode_value(&value), Err(PolicyError::Format)));
        }
        for count in [INPUTS - 1, INPUTS + 1] {
            let mut value = original.clone();
            value["inputs"] = serde_json::json!(vec![original["inputs"][0].clone(); count]);
            assert!(matches!(decode_value(&value), Err(PolicyError::Count)));
        }
        for size in [serde_json::json!(true), serde_json::json!(-1), serde_json::json!(1.5)] {
            let mut value = original.clone(); value["inputs"][0]["size"] = size;
            assert!(matches!(decode_value(&value), Err(PolicyError::Format)));
        }
        for (index, size) in [(0, FILE_BYTES), (MANIFEST, MANIFEST_BYTES + 1), (52, CONTROL_LIMITS[0] + 1)] {
            let mut value = original.clone(); value["inputs"][index]["size"] = serde_json::json!(size);
            assert!(matches!(decode_value(&value), Err(PolicyError::Bounds)));
        }
        let mut value = original; value["inputs"][0]["sha256"] = serde_json::json!("0".repeat(64));
        assert!(matches!(decode_value(&value), Err(PolicyError::Format)));
        assert!(matches!(decode_profile(&vec![b' '; PROFILE_BYTES + 1], &profile_bindings("")), Err(PolicyError::Bounds)));
    }
    #[test]
    fn retained_profile_reuses_schema_without_claiming_current_compile_authority() {
        let mut value = profile_value();
        value["sourceCommit"] = serde_json::json!("b".repeat(40));
        value["coreVersion"] = serde_json::json!("0.2.9");
        let raw = serde_json::to_vec(&value).unwrap();
        let image = hex(&Sha256::digest(&raw));
        let retained = decode_retained_profile(&raw, &image).unwrap();
        assert_eq!(retained.inputs.image(), Ok(image.as_str()));
        assert_eq!(retained.core_version, "0.2.9");
        assert!(matches!(decode_profile(&raw, &profile_bindings(&image)), Err(PolicyError::Binding)));
        assert!(matches!(decode_retained_profile(b"invalid JSON", &image), Err(PolicyError::Hash)));
        for (field, replacement) in [("target", "aarch64-pc-windows-msvc"), ("purpose", "other"),
            ("coreVersion", "x\ncommand")] {
            let mut wrong = value.clone(); wrong[field] = serde_json::json!(replacement);
            let bytes = serde_json::to_vec(&wrong).unwrap();
            assert!(decode_retained_profile(&bytes, &hex(&Sha256::digest(&bytes))).is_err(), "{field}");
        }
        let mut rows = value;
        rows["inputs"][7]["sha256"] = serde_json::json!("f".repeat(64));
        let bytes = serde_json::to_vec(&rows).unwrap();
        assert!(matches!(decode_retained_profile(&bytes, &hex(&Sha256::digest(&bytes))), Err(PolicyError::Binding)));
        assert!(fixture().selection_hashes().is_err());
    }

}
