//! DATA-only regressions for the actual private transition/finality helpers.
//! Integers below stand for observations in DATA; none is passed to any Win32
//! operation or represented as native qualification. Real handle/CPython tests
//! must use Root's separately authorized original EditOwner installed fixture.
use super::*;

fn data() -> Box<Metadata> {
    let mut value = Box::<Metadata>::new_uninit();
    // Metadata has only integer/pointer POD fields; no native allocation/call.
    unsafe { value.as_mut_ptr().write_bytes(0, 1); value.assume_init() }
}
fn ready_data(a: &mut Metadata) {
    a.side = 1; a.prepared = 2; a.pid = 11; a.thread = 12;
    a.nonce = [7; 32]; a.attributes_ready = 1;
    for (i, c) in a.channels.iter_mut().enumerate() {
        c.original = (100 + i * 12) as F::HANDLE;
        c.pipe_attempted = 1; c.pipe_returned = 1; c.pipe_ntstatus = F::STATUS_SUCCESS;
        c.pipe_custody = 2; c.pipe_output_seen = 1; c.pipe_output = c.original;
        c.pipe_iosb_seen = 1; c.pipe_iosb_status = F::STATUS_SUCCESS;
        c.pipe_information = PIPE_FILE_CREATED;
        c.client = (104 + i * 12) as F::HANDLE;
        c.event = (108 + i * 12) as F::HANDLE;
        c.claimed = 1; c.state = State::Complete as u32;
        c.operation = 3; c.return_seen = 2; a.inherited[i] = c.client;
    }
}
fn created_data(a: &mut Metadata) {
    ready_data(a);
    a.create_attempted = 1; a.create_returned = 1; a.create_bool = 1;
    a.process.hProcess = 200usize as F::HANDLE; a.process.hThread = 204usize as F::HANDLE;
    a.process.dwProcessId = 21; a.process.dwThreadId = 22;
    // Explicit DATA receipt, never generated by a fake CreateProcess.
    a.create_custody = 2; a.process_original = 1; a.thread_original = 1;
}

#[test]
fn retirement_and_each_original_receipt_revoke_creation() {
    let mut a = data(); ready_data(&mut a);
    assert!(creation_ready(&a)); // conditional DATA predicate, no native admission
    a.startup_retired = 1; assert!(!creation_ready(&a)); a.startup_retired = 0;
    a.attributes_deleted = 2; assert!(!creation_ready(&a)); a.attributes_deleted = 0;
    for i in 0..3 {
        a.channels[i].client_close = 2; assert!(!creation_ready(&a));
        a.channels[i].client_close = 0;
        a.channels[i].original_close = 1; assert!(!creation_ready(&a));
        a.channels[i].original_close = 0;
        a.channels[i].event_close = 3; assert!(!creation_ready(&a));
        a.channels[i].event_close = 0;
        a.channels[i].state = State::Pending as u32; assert!(!creation_ready(&a));
        a.channels[i].state = State::Complete as u32;
    }
    a.create_attempted = 1; assert!(!creation_ready(&a));
}
#[test]
fn original_inheritance_roster_cannot_be_changed() {
    let mut a = data(); ready_data(&mut a);
    for i in 0..3 {
        let original = a.inherited[i];
        a.inherited[i] = null_mut(); assert!(!creation_ready(&a));
        a.inherited[i] = a.channels[(i + 1) % 3].client; assert!(!creation_ready(&a));
        a.inherited[i] = original;
    }
}
#[test]
fn rejected_process_outputs_never_authorize_control_or_ack() {
    let mut a = data(); created_data(&mut a);
    for value in [0usize, usize::MAX, usize::MAX - 1, usize::MAX - 3, usize::MAX - 5] {
        a.process.hProcess = value as F::HANDLE;
        assert!(!admitted_process_outputs(&a));
    }
    a.process.hProcess = a.process.hThread; assert!(!admitted_process_outputs(&a));
    a.process.hProcess = a.channels[0].client; assert!(!admitted_process_outputs(&a));
    a.process.hProcess = 200usize as F::HANDLE;
    a.process.dwProcessId = a.pid; assert!(!admitted_process_outputs(&a));
    a.process.dwProcessId = 21; a.process.dwThreadId = 0;
    assert!(!admitted_process_outputs(&a));
    a.process.dwThreadId = 22;
    // Successful BOOL alone cannot bypass a rejected-output custody receipt.
    a.create_custody = 3; a.process_original = 0; a.thread_original = 0;
    assert!(!process_control_ready(&a)); assert!(!acknowledgement_ready(&a));
    assert!(!no_child_effect(&a)); assert!(!parent_consumers_settled(&a));
}
#[test]
fn precreation_and_repeated_acknowledgements_are_rejected() {
    let a = data();
    assert!(!valid_acknowledgement(&a, &handoff(0, 0, &[0; 32], true)));
    let mut a = data(); created_data(&mut a);
    let ack = handoff(a.pid, a.process.dwProcessId, &a.nonce, true);
    assert!(valid_acknowledgement(&a, &ack));
    for index in [0, 8, 12, 16, 20, 24, 28, 32, 64, 95] {
        let mut wrong = ack; wrong[index] ^= 1;
        assert!(!valid_acknowledgement(&a, &wrong));
    }
    assert!(!valid_acknowledgement(&a, &ack[..95]));
    a.handoff = 1; assert!(!valid_acknowledgement(&a, &ack));
    a.handoff = 0; a.unknown = 1; assert!(!valid_acknowledgement(&a, &ack));
    a.unknown = 0; a.first = BAD_STATE; assert!(!valid_acknowledgement(&a, &ack));
}
#[test]
fn successful_zero_is_complete_not_eof_and_counts_are_bounded() {
    assert_eq!(completed_state(1, 0, 1, 0, 64), State::Complete);
    assert_eq!(completed_state(1, 0, 2, 7, 64), State::Complete); // partial write
    assert_eq!(completed_state(1, 0, 1, 65, 64), State::Unknown);
    assert_eq!(completed_state(0, F::ERROR_IO_INCOMPLETE, 1, 0, 64), State::Pending);
    assert_eq!(completed_state(0, F::ERROR_BROKEN_PIPE, 1, 0, 64), State::Eof);
    assert_eq!(completed_state(0, F::ERROR_BROKEN_PIPE, 2, 0, 64), State::Unknown);
    assert_eq!(completed_state(0, F::ERROR_OPERATION_ABORTED, 1, 0, 64), State::Cancelled);
    assert_eq!(completed_state(0, F::ERROR_NOT_FOUND, 1, 0, 64), State::Unknown);
}
#[test]
fn cancellation_return_cannot_finish_or_replace_the_pending_operation() {
    for (value, error) in [(1, 0), (0, F::ERROR_NOT_FOUND), (0, 5)] {
        let mut a = data();
        let c = &mut a.channels[0];
        c.state = State::Pending as u32; c.operation = 2; c.generation = 19;
        c.requested = 64; c.return_seen = 2;
        c.cancel_attempted = 1; c.cancel_return = value; c.cancel_error = error;
        accept_cancel_result(&mut a, Role::Input);
        let c = &a.channels[0];
        assert_eq!(state(c.state), State::Pending);
        assert_eq!((c.generation, c.operation, c.requested), (19, 2, 64));
        assert!(!known_complete(c)); assert!(!parent_consumers_settled(&a));
        assert_eq!(a.unknown != 0, value == 0 && error != F::ERROR_NOT_FOUND);
    }
}
#[test]
fn first_failure_unknown_and_lifetime_budget_are_sticky() {
    let mut a = data();
    fail(&mut a, 5, false); fail(&mut a, 6, true);
    assert_eq!(a.first, 5); assert_eq!(a.unknown, 1);
    a.calls = LIFETIME_ENTRIES - SETTLEMENT_RESERVE;
    assert!(entry(&mut a, false).is_err());
    assert!(entry(&mut a, true).is_ok()); returned(&mut a, 1, 0);
    a.calls = LIFETIME_ENTRIES; assert!(entry(&mut a, true).is_err());
    a.calls = 0; a.call_seen = 1; assert!(entry(&mut a, true).is_err());
    assert_eq!(a.first, 5); assert_eq!(a.unknown, 1);
}
#[test]
fn memory_reclamation_requires_all_independent_consumers() {
    let mut a = data();
    assert!(parent_consumers_settled(&a)); // never entered; safe memory-only free
    a.channels[0].state = State::Pending as u32; assert!(!parent_consumers_settled(&a));
    a.channels[0].state = State::Idle as u32;
    a.unknown = 1; assert!(!parent_consumers_settled(&a)); a.unknown = 0;
    a.call_seen = 1; assert!(!parent_consumers_settled(&a)); a.call_seen = 0;
    created_data(&mut a);
    a.exit_seen = 1; a.process_close = 2; a.thread_close = 2;
    a.attributes_deleted = 2;
    for c in &mut a.channels {
        c.original_close = 2; c.client_close = 2; c.event_close = 2;
        c.state = State::Closed as u32;
    }
    assert!(parent_consumers_settled(&a)); // only a DATA finality conjunction
    a.thread_close = 3; assert!(!parent_consumers_settled(&a)); a.thread_close = 2;
    a.channels[1].event_close = 1; assert!(!parent_consumers_settled(&a));
    a.channels[1].event_close = 2;
    a.channels[2].uncertain = 1; assert!(!parent_consumers_settled(&a));
}
#[test]
fn definitive_false_is_not_an_opaque_or_partial_create() {
    let mut a = data();
    a.create_attempted = 1; assert!(!no_child_effect(&a));
    a.create_returned = 1; a.create_bool = 0; a.create_custody = 1;
    assert!(no_child_effect(&a));
    a.process.dwProcessId = 21; assert!(!no_child_effect(&a));
    a.process.dwProcessId = 0; a.create_custody = 3; assert!(!no_child_effect(&a));
}
#[test]
fn native_destinations_and_metadata_have_disjoint_pinned_storage() {
    assert!(size_of::<Arena>() + 64 * 1024 <= ARENA_BYTES);
    assert_eq!(BUFFER_BYTES, 65_536); assert_eq!(HANDOFF_BYTES, 96);
    assert!(std::mem::offset_of!(Arena, metadata)
        >= std::mem::offset_of!(Arena, launch) + size_of::<LaunchStorage>());
    assert!(std::mem::offset_of!(Arena, launch) >= size_of::<[IoSlot; 3]>());
    assert_eq!(size_of::<IO::IO_STATUS_BLOCK>(), 16);
    assert_eq!(std::mem::offset_of!(IO::IO_STATUS_BLOCK, Information), 8);
    assert_eq!(size_of::<F::UNICODE_STRING>(), 16);
    assert_eq!(std::mem::offset_of!(F::UNICODE_STRING, Buffer), 8);
    assert_eq!(size_of::<OBJECT_ATTRIBUTES>(), 48);
    assert_eq!(std::mem::offset_of!(OBJECT_ATTRIBUTES, ObjectName), 16);
    assert!(std::mem::offset_of!(LaunchStorage, descriptor) >= size_of::<[PipeCreateStorage; 3]>());
    assert!(std::mem::offset_of!(PipeCreateStorage, iosb)
        >= std::mem::offset_of!(PipeCreateStorage, output) + size_of::<F::HANDLE>());
    assert!(std::mem::offset_of!(PipeCreateStorage, name)
        >= std::mem::offset_of!(PipeCreateStorage, iosb) + size_of::<IO::IO_STATUS_BLOCK>());
    assert!(std::mem::offset_of!(PipeCreateStorage, unicode)
        >= std::mem::offset_of!(PipeCreateStorage, name) + size_of::<[u16; 160]>());
    assert!(std::mem::offset_of!(PipeCreateStorage, attributes)
        >= std::mem::offset_of!(PipeCreateStorage, unicode) + size_of::<F::UNICODE_STRING>());
    assert!(std::mem::offset_of!(PipeCreateStorage, timeout)
        >= std::mem::offset_of!(PipeCreateStorage, attributes) + size_of::<OBJECT_ATTRIBUTES>());
    assert!(Role::Input.reads(2)); assert!(!Role::Input.reads(1));
    assert!(Role::Output.reads(1)); assert!(!Role::Error.reads(2));
}

#[test]
fn pipe_creation_requests_documented_directional_rights_and_native_flags_only() {
    let required = FS::READ_CONTROL | FS::SYNCHRONIZE | FS::FILE_READ_ATTRIBUTES;
    for role in [Role::Input, Role::Output, Role::Error] {
        let server_data = if role == Role::Input { FS::FILE_WRITE_DATA } else { FS::FILE_READ_DATA };
        let client_data = if role == Role::Input { FS::FILE_READ_DATA } else { FS::FILE_WRITE_DATA };
        assert_eq!(pipe_access(role, false), required | server_data);
        assert_eq!(pipe_access(role, true), required | client_data);
        assert_eq!(pipe_access(role, false) & 3, server_data);
        assert_eq!(pipe_access(role, true) & 3, client_data);
        assert_eq!(pipe_access(role, false) & FS::FILE_APPEND_DATA, 0);
        assert_eq!(pipe_access(role, true) & FS::FILE_APPEND_DATA, 0);
        assert_eq!(pipe_server_share(role),
            if role == Role::Input { FS::FILE_SHARE_READ } else { FS::FILE_SHARE_WRITE });
    }
    assert_eq!(PIPE_FILE_CREATE, 2); assert_eq!(PIPE_FILE_CREATED, 2);
    assert_eq!(PIPE_BYTE_STREAM_TYPE | PIPE_REJECT_REMOTE_CLIENTS, 2); // NOT Win32 flag8
    assert_eq!((PIPE_BYTE_STREAM_MODE, PIPE_QUEUE_OPERATION, PIPE_CREATE_OPTIONS), (0, 0, 0));
    assert_eq!(PIPE_DEFAULT_TIMEOUT_100NS, -500_000); // same50ms pipe default, not an owner clock
}
#[test]
fn only_definite_nt_returns_allow_pipe_output_observation() {
    assert!(definite_pipe_return(F::STATUS_SUCCESS));
    assert!(definite_pipe_return(0xc000_0022u32 as i32));
    for status in [F::STATUS_PENDING, 1, 0x4000_0000, 0x8000_0005u32 as i32] {
        assert!(!definite_pipe_return(status));
    }
}
#[test]
fn successful_nt_status_needs_created_iosb_and_unique_positive_output() {
    let mut a = data();
    let candidate = 512usize as F::HANDLE; // inert DATA, never given to any syscall
    assert!(admitted_pipe_output(&a, candidate, F::STATUS_SUCCESS, PIPE_FILE_CREATED));
    for invalid in [0usize, usize::MAX, usize::MAX - 1, usize::MAX - 3, usize::MAX - 5] {
        assert!(!admitted_pipe_output(&a, invalid as F::HANDLE, F::STATUS_SUCCESS, PIPE_FILE_CREATED));
    }
    assert!(!admitted_pipe_output(&a, candidate, F::STATUS_PENDING, PIPE_FILE_CREATED));
    assert!(!admitted_pipe_output(&a, candidate, F::STATUS_SUCCESS, 1)); // FILE_OPENED is not FILE_CREATE
    a.channels[0].event = candidate;
    assert!(!admitted_pipe_output(&a, candidate, F::STATUS_SUCCESS, PIPE_FILE_CREATED));
    a.channels[0].event = null_mut(); a.channels[1].client = candidate;
    assert!(!admitted_pipe_output(&a, candidate, F::STATUS_SUCCESS, PIPE_FILE_CREATED));
    a.channels[1].client = null_mut(); a.process.hProcess = candidate;
    assert!(!admitted_pipe_output(&a, candidate, F::STATUS_SUCCESS, PIPE_FILE_CREATED));
}
#[test]
fn unreturned_and_nondefinite_pipe_creation_never_become_empty_consumed_slots() {
    let mut a = data();
    a.channels[0].pipe_attempted = 1; a.channels[0].original_close = 1;
    assert!(!pipe_creation_consumed(&a.channels[0]));
    assert!(!parent_consumers_settled(&a));
    a.channels[0].pipe_returned = 1; a.channels[0].pipe_ntstatus = F::STATUS_PENDING;
    let _ = pipe_create_unknown(&mut a, Role::Input, F::STATUS_PENDING as u32);
    assert_eq!(a.unknown, 1); assert_eq!(a.channels[0].pipe_custody, 3);
    assert_eq!((a.channels[0].pipe_output_seen, a.channels[0].pipe_iosb_seen), (0, 0));
    assert!(a.channels[0].original.is_null());
    assert_eq!(a.channels[0].original_close, 1);
    assert!(!pipe_created_original(&a.channels[0]));
    assert!(!pipe_creation_consumed(&a.channels[0]));
    assert!(!parent_consumers_settled(&a));
}
#[test]
fn definite_failed_pipe_creation_requires_observed_null_output_not_stale_iosb() {
    let mut a = data();
    let c = &mut a.channels[0];
    c.pipe_attempted = 1; c.pipe_returned = 1; c.pipe_ntstatus = 0xc000_0022u32 as i32;
    c.pipe_custody = 1; c.pipe_output_seen = 1; c.original_close = 4;
    assert_eq!(c.pipe_iosb_seen, 0); // the authoritative error need not initialize IOSB
    assert!(pipe_creation_consumed(c)); assert!(parent_consumers_settled(&a));
    a.channels[0].pipe_output_seen = 0; assert!(!parent_consumers_settled(&a));
    a.channels[0].pipe_output_seen = 1;
    a.channels[0].pipe_output = 512usize as F::HANDLE;
    assert!(!pipe_creation_consumed(&a.channels[0]));
    a.channels[0].pipe_output = null_mut(); a.channels[0].pipe_ntstatus = F::STATUS_PENDING;
    assert!(!pipe_creation_consumed(&a.channels[0]));
}
#[test]
fn launch_and_reclamation_require_the_actual_pipe_creation_custody_receipt() {
    let mut a = data(); ready_data(&mut a);
    assert!(creation_ready(&a));
    for i in 0..3 {
        a.channels[i].pipe_custody = 3; assert!(!creation_ready(&a));
        a.channels[i].pipe_custody = 2;
        a.channels[i].pipe_output_seen = 0; assert!(!creation_ready(&a));
        a.channels[i].pipe_output_seen = 1;
        a.channels[i].pipe_iosb_status = F::STATUS_PENDING; assert!(!creation_ready(&a));
        a.channels[i].pipe_iosb_status = F::STATUS_SUCCESS;
        a.channels[i].pipe_information = 1; assert!(!creation_ready(&a));
        a.channels[i].pipe_information = PIPE_FILE_CREATED;
        assert!(!pipe_creation_consumed(&a.channels[i])); // claimed is not closed
        a.channels[i].original_close = 2;
        assert!(pipe_creation_consumed(&a.channels[i]));
        assert!(!creation_ready(&a)); // that positive close permanently revokes create
        a.channels[i].original_close = 0;
    }
}
