import { useState } from 'react';
import type { Catalog, HelpContent } from '../types.ts';
import { Badge, DisabledAction, EmptyState, HelpButton, PageHeading, SectionHeading } from '../components/Common.tsx';
import { Icon } from '../components/Icon.tsx';

export function Credentials({ catalog, onHelp }: { catalog: Catalog | null; onHelp: (help: HelpContent) => void }) {
  const [filter, setFilter] = useState('');
  const credentials = catalog?.credentials.filter((entry) => `${entry.name} ${entry.platform} ${entry.what}`.toLocaleLowerCase().includes(filter.toLocaleLowerCase())) ?? [];
  return <>
    <PageHeading eyebrow="CREDENTIALS & SIGNING" title="Private by design." description="Understand what you will need before connecting accounts or importing private signing assets." />
    <div className="privacy-hero card"><div className="privacy-illustration"><Icon name="lock" size={42} /></div><div><Badge tone="info">No secrets collected</Badge><h2>Your credentials stay out of this draft.</h2><p>Secure vault storage, asset import, and account login are not implemented yet. This screen is a requirements guide only. Do not paste tokens, passwords, private keys, or service-account JSON into project settings.</p></div></div>
    <div className="three-card-grid">{[{ icon: 'android' as const, title: 'Android signing', description: 'A keystore, signing policy, and the matching upload identity.' }, { icon: 'apple' as const, title: 'Apple signing', description: 'Certificates, provisioning, and protected App Store access.' }, { icon: 'github' as const, title: 'GitHub access', description: 'Reviewed repository access and protected release environments.' }].map((item) => <div className="card credential-summary" key={item.title}><span className="soft-icon"><Icon name={item.icon} size={23} /></span><h3>{item.title}</h3><p>{item.description}</p><Badge>Unknown · not collected</Badge></div>)}</div>
    <section className="card"><SectionHeading title="Core requirement catalogue" description="Conditional requirements are guidance, not proof that credentials exist or work."><label className="search-field"><Icon name="search" size={16} /><span className="sr-only">Find a credential requirement</span><input type="search" value={filter} onChange={(event) => setFilter(event.target.value)} placeholder="Find a requirement…" /></label></SectionHeading>
      {credentials.length ? <div className="credential-list">{credentials.map((credential, index) => <article key={`${credential.name}-${index}`}><div className="credential-row-heading"><div className="inline-heading"><h3>{credential.name}</h3><HelpButton content={{ ...credential, label: credential.name }} onHelp={onHelp} /></div><Badge>Not verified</Badge></div><p>{credential.what}</p><div className="credential-meta"><span>{credential.platform}</span><span>{credential.kind}</span><span>{credential.stages.join(' · ')}</span></div><p className="credential-when">{credential.requiredWhen}</p></article>)}</div> : <EmptyState compact icon="key" title={filter ? 'No matching requirement' : 'No native credential catalogue loaded'} description={filter ? 'Try a platform name or a different keyword.' : 'The connected core supplies exact credential names, conditional requiredness, formats, and recovery guidance. Browser examples never invent credential status.'} />}
    </section>
    <div className="two-card-grid"><section className="card"><SectionHeading title="Secure asset import" description="Native pickers will register and validate private assets without moving or overwriting originals." /><DisabledAction label="Import signing asset" icon="key" reason="Secure vault, encrypted private asset custody, and native import validation are not implemented." /></section><section className="card"><SectionHeading title="Credential verification" description="Configured and service-verified will be tracked separately for every required credential." /><DisabledAction label="Verify credentials" icon="shield" reason="Signing and protected online credential checks are not implemented. Nothing has been read or tested." /></section></div>
  </>;
}
