import { useEffect, useId, useRef, useState } from 'react';
import {
  canApplyWorkflows, currentWorkflowApplyBinding, workflowApplyHelp, workflowDisplayDiff,
  workflowEditNotice, workflowNoOp,
} from '../githubWorkflowEdit.ts';
import type { GitHubWorkflowEditState, WorkflowApplyBinding } from '../githubWorkflowEdit.ts';
import type { GitHubWorkflowEditController } from '../githubWorkflowEditController.ts';
import type { WorkflowPreparedView } from '../githubWorkflowEditTypes.ts';
import type { GitHubSetupState } from '../githubSetupController.ts';
import type { ProjectSession } from '../drafts.ts';
import type { HelpContent } from '../types.ts';
import { Badge, HelpButton, SectionHeading } from './Common.tsx';
import { Icon } from './Icon.tsx';

function WorkflowFiles({ view }: { view: WorkflowPreparedView }) {
  return <div className="review-table-wrap workflow-files"><table className="review-table">
    <caption>Complete native workflow inventory — all four or refuse</caption>
    <thead><tr><th scope="col">Fixed destination</th><th scope="col">Action</th><th scope="col">Native observation</th><th scope="col">Generated bytes</th></tr></thead>
    <tbody>{view.files.map((file) => <tr key={file.id}>
      <th scope="row"><code>{file.path}</code></th><td>{file.action === 'create' ? 'Create absent file' : 'Preserve exact original'}</td>
      <td>{file.observed.state === 'absent' ? 'Observed absent' : <>{file.observed.byteLength.toLocaleString()} bytes<code>{file.observed.sha256}</code></>}</td>
      <td>{file.generated.byteLength.toLocaleString()} bytes<code>{file.generated.sha256}</code></td>
    </tr>)}</tbody>
  </table></div>;
}
function WorkflowText({ view }: { view: WorkflowPreparedView }) {
  return <div className="github-workflows">{view.files.map((file) => <details className="github-workflow" key={file.id}>
    <summary><code>{file.path}</code><Badge>{file.action === 'create' ? 'Full added text' : 'Full unchanged context'}</Badge></summary>
    <p className="github-workflow-meta">Complete core-generated UTF-8 text, {file.generated.byteLength.toLocaleString()} bytes. {file.action === 'preserve' ? 'The native core compared complete original bytes; this display shows the identical generated text, not arbitrary existing YAML.' : 'Every added line is shown. This is not a replacement or merge.'}</p>
    <pre tabIndex={0} aria-label={`${file.action === 'create' ? 'Complete added diff' : 'Complete unchanged generated context'} for ${file.path}`}><code>{workflowDisplayDiff(file)}</code></pre>
  </details>)}</div>;
}
function WorkflowReview({ view }: { view: WorkflowPreparedView }) {
  return <div className="save-review workflow-review">
    <div className="review-basis"><Icon name="shield" size={18} /><div><strong>{workflowNoOp(view) ? 'No file writes are planned' : 'Only absent callers will be created'}</strong><p>{workflowNoOp(view) ? 'Explicit confirmation still rechecks the original files and waits for native settlement; a passive digest match is never a verified no-op.' : 'One differing, unsafe or stale file refuses the bundle. This is recoverable installation, not an instantaneous four-file atomic rename.'}</p></div></div>
    <WorkflowFiles view={view} />
    <dl className="github-facts">
      <div><dt>Toolkit repository</dt><dd><code>{view.tooling.repository}</code></dd></div>
      <div><dt>Toolkit commit · format-only</dt><dd><code>{view.tooling.sha}</code></dd></div>
      <div><dt>Core / resource version</dt><dd>{view.templateSet.coreVersion} / {view.templateSet.resourceVersion}</dd></div>
      <div><dt>Resource identity SHA256</dt><dd><code>{view.templateSet.resourceSha256}</code></dd></div>
      <div className="github-fact-wide"><dt>Schema reference · informational, not fetched or saved</dt><dd><code>{view.tooling.schemaReference}</code></dd></div>
    </dl>
    <p className="save-note">{view.createDirectories.length > 0 ? <>Missing directories to create: {view.createDirectories.map((path, index) => <span key={path}>{index > 0 && ', '}<code>{path}</code></span>)}. </> : 'Existing ancestors are preserved. '}New directories use 0755; new files request 0644 subject to inherited umask. Exact-preserved originals are not rewritten or chmodded.</p>
    <WorkflowText view={view} />
    <p className="review-caution">Draft validation was required for this plan, but no configuration save is required or performed. The toolkit ref and template compatibility are not remotely verified. GitHub, credentials, unknown workflow siblings, .gitignore, Git/index state and release operations are outside this plan.</p>
  </div>;
}
function WorkflowConfirmation({ view, binding, allowed, onCancel, onConfirm }: {
  view: WorkflowPreparedView; binding: WorkflowApplyBinding; allowed: boolean; onCancel: () => void; onConfirm: () => void;
}) {
  const dialog = useRef<HTMLDialogElement>(null);
  const titleId = useId(); const checkboxId = useId();
  const [reviewed, setReviewed] = useState(false);
  const noOp = workflowNoOp(view);
  useEffect(() => {
    const element = dialog.current;
    if (element && !element.open) element.showModal();
    return () => { if (element?.open) element.close(); };
  }, []);
  return <dialog ref={dialog} className="save-confirm-dialog workflow-confirm-dialog" aria-labelledby={titleId} onCancel={onCancel}>
    <div className="dialog-content"><span className="eyebrow">EXPLICIT LOCAL WORKFLOW REVIEW</span>
      <h2 id={titleId}>{noOp ? 'Confirm four unchanged callers?' : 'Apply this four-caller bundle?'}</h2>
      <p>This confirms the native plan made from draft revision {binding.draftRevision} and toolkit pin <code>{view.tooling.repository}@{view.tooling.sha}</code>, not later edits. {noOp ? 'The native owner must recheck and fully settle before unchanged is confirmed.' : 'Absent files may be created one by one. A late cancellation is not proof of rollback.'}</p>
      <WorkflowFiles view={view} />
      {view.createDirectories.length > 0 && <p>Missing directories included: {view.createDirectories.map((path, index) => <span key={path}>{index > 0 && ', '}<code>{path}</code></span>)}.</p>}
      <details className="workflow-confirm-text"><summary>Recheck the complete generated diff</summary><WorkflowText view={view} /></details>
      <label className="save-confirm-choice" htmlFor={checkboxId}><input id={checkboxId} type="checkbox" checked={reviewed} onChange={(event) => setReviewed(event.target.checked)} />I reviewed all four paths and complete text. This only installs or preserves local callers; it does not save configuration, contact GitHub or execute a release.</label>
      {!allowed && <p className="review-caution" role="alert">This review is no longer current. No Apply can be submitted from this confirmation.</p>}
      <div className="button-row"><button type="button" autoFocus className="button secondary" onClick={onCancel}>Keep reviewing</button><button type="button" className="button primary" disabled={!reviewed || !allowed} onClick={onConfirm}>{noOp ? 'Confirm unchanged plan' : 'Apply reviewed local files'}</button></div>
    </div>
  </dialog>;
}

export function GitHubWorkflowApply({ state, controller, setup, projects, selectedId, detailed, onShowProject, onHelp }: {
  state: GitHubWorkflowEditState;
  controller: GitHubWorkflowEditController;
  setup: GitHubSetupState;
  projects: Record<string, ProjectSession>;
  selectedId: string | null;
  detailed: boolean;
  onShowProject: (projectId: string) => void;
  onHelp: (help: HelpContent) => void;
}) {
  const [confirmation, setConfirmation] = useState<WorkflowApplyBinding | null>(null);
  const attempt = state.attempt;
  const owner = attempt?.projection ?? state.unknownEvidence ?? state.status?.active ?? state.status?.lastTerminal ?? null;
  const projectId = owner?.projectId ?? attempt?.binding.projectId ?? null;
  const project = projectId && Object.hasOwn(projects, projectId) ? projects[projectId] ?? null : null;
  const selected = selectedId && Object.hasOwn(projects, selectedId) ? projects[selectedId] ?? null : null;
  const notice = workflowEditNotice(state);
  const startReason = controller.startReason();
  const binding = currentWorkflowApplyBinding(state);
  const mayApply = canApplyWorkflows(state, selected, setup);
  const owned = Boolean(attempt && owner && attempt.sessionId === owner.sessionId && attempt.binding.windowGeneration === owner.ownerGeneration);
  const terminal = owner?.phase === 'final' || owner?.phase === 'unknown';
  const showReview = detailed && selectedId === projectId && owner?.prepared !== null && owner?.prepared !== undefined;
  const applyPending = Boolean(attempt?.applyClaimed || owner?.applySubmitted);
  const mayClose = state.mode === 'native' && attempt !== null && !attempt.handled && !attempt.closeRequested && !state.generationLost && !state.nativeBlocked &&
    (!owner || owned && !terminal);
  useEffect(() => {
    if (confirmation && (!detailed || selectedId !== projectId || !canApplyWorkflows(state, selected, setup, confirmation))) setConfirmation(null);
  }, [state, setup, selected, selectedId, projectId, detailed, confirmation]);
  if (!detailed && !notice) return null;
  return <section className="card native-workflow-panel" aria-label="Local GitHub workflow files">
    <SectionHeading title={notice?.title ?? 'Local workflow files · separate native review'} description={project ? `Original local operation for ${project.project.name}. Configuration drafts remain separate and unsaved.` : 'Create absent callers or preserve exact existing bytes. Passive previews never supply Apply authority.'}>
      <HelpButton content={workflowApplyHelp} onHelp={onHelp} />
    </SectionHeading>
    {notice && <div className={`notice notice-${notice.tone === 'danger' ? 'danger' : notice.tone === 'warning' ? 'warning' : 'info'}`} role={notice.tone === 'danger' ? 'alert' : 'status'} aria-live="polite"><Icon name="shield" size={18} /><div><p>{notice.detail}</p>{notice.code && <span className="error-code">{notice.code}</span>}</div></div>}
    {owner && !owned && <p className="review-caution">Read-only native operation summary. This renderer has not adopted its review token or submitted an Apply.</p>}
    {state.generationLost && applyPending && <p className="review-caution">The document generation changed. The original submitted outcome is retained for observation only; no review authority can be reattached.</p>}
    {state.nativeBlocked && owner?.phase === 'final' && <p className="review-caution" role="alert">This original result is retained, but other native cleanup remains unverified. Further file edits are disabled; do not repeat Apply or clear recovery evidence.</p>}
    {applyPending && <p className="save-note">This status belongs to the originally submitted project, draft and pin. Newer selections and configuration edits are kept; workflow installation never marks a draft clean.</p>}
    {showReview && owner?.prepared && <WorkflowReview view={owner.prepared.view} />}
    {owner?.conflict && <div className="workflow-conflict"><h3>Observed differing callers · no Apply token</h3><ul>{owner.conflict.conflicts.map((row) => <li key={row.id}><strong>{row.id}</strong><span>{row.observed.byteLength.toLocaleString()} observed bytes</span><code>{row.observed.sha256}</code></li>)}</ul><p>Only summaries actually obtained by the original capture are shown. Existing YAML is not exposed; no subset, force or overwrite option is available.</p></div>}
    {owner && (terminal || owner.phase === 'finalizing') && <dl className="save-outcome-facts" aria-label="Independent native workflow outcome facts"><div><dt>Transaction effect</dt><dd>{owner.coreOutcome?.effect ?? 'Not reported'}</dd></div><div><dt>Journal</dt><dd>{owner.coreOutcome?.journal ?? 'Not reported'}</dd></div><div><dt>Core resources</dt><dd>{owner.coreOutcome?.resources ?? 'Not reported'}</dd></div><div><dt>Native finality</dt><dd>{owner.nativeFinality}{owner.lateSettled ? ' · late settlement recorded' : ''}</dd></div></dl>}
    <div className="button-row save-actions">
      {detailed && <button type="button" className="button secondary" disabled={startReason !== null} aria-describedby="github-workflow-start-reason" onClick={() => controller.start()}><Icon name={startReason ? 'lock' : 'github'} size={17} />Review local workflow files</button>}
      {showReview && owned && !terminal && owner?.prepared && <button type="button" className="button primary" disabled={!mayApply || !binding} onClick={() => { if (binding && mayApply) setConfirmation(binding); }}>{applyPending ? 'Apply already requested' : workflowNoOp(owner.prepared.view) ? 'Review unchanged confirmation' : 'Confirm reviewed local files'}<Icon name={mayApply ? 'check' : 'lock'} size={16} /></button>}
      {mayClose && <button type="button" className="button secondary" onClick={() => controller.requestClose()}>{applyPending ? 'Request cancellation' : 'Close workflow review / keep draft'}</button>}
      {project && (!detailed || selectedId !== projectId) && <button type="button" className="button secondary" onClick={() => onShowProject(project.project.id)}>View original {terminal ? 'workflow outcome' : 'workflow review'}<Icon name="arrow" size={16} /></button>}
      {state.mode === 'native' && <button type="button" className="button small secondary" disabled={state.readPending} onClick={() => void controller.checkStatus()}><Icon name="refresh" size={15} className={state.readPending ? 'spin' : ''} />{state.readPending ? 'Checking status…' : 'Check original workflow status'}</button>}
    </div>
    {detailed && <p id="github-workflow-start-reason" className="save-note">{startReason ?? 'Starts a fresh original-file observation and native review. It ignores all supplied comparison assertions and does not apply the passive preview.'}</p>}
    {showReview && !terminal && <p className="save-note">Selection, draft/baseline, toolkit pin, service/runtime or document changes retire this review before Apply. The native review lifetime is nonrenewable. Nothing is silently rebased, reprepared or retried.</p>}
    {confirmation && owner?.prepared && <WorkflowConfirmation view={owner.prepared.view} binding={confirmation} allowed={detailed && selectedId === projectId && canApplyWorkflows(state, selected, setup, confirmation)} onCancel={() => setConfirmation(null)} onConfirm={() => { controller.apply(confirmation); setConfirmation(null); }} />}
  </section>;
}
